### ISSUE TITLE
LOW UPTIME not work 

### ISSUE THREAD

**Issue by Oxicode** [richardforth/apache2buddy#108]
![image](https://cloud.githubusercontent.com/assets/1320709/22599797/080249ec-ea06-11e6-83e2-6b11d5edaf54.png)

![image](https://cloud.githubusercontent.com/assets/1320709/22599804/11ae9acc-ea06-11e6-9426-d81f986d5753.png)

My Server
![image](https://cloud.githubusercontent.com/assets/1320709/22599821/1eca737a-ea06-11e6-9a57-0ca0a0d112dd.png)

**Comment by richardforth** [comment]
apache uptime, not server uptime

**Comment by richardforth** [comment]
apache has bene running 1 hour 29m 09s

your server has been up for 101d 14h 21m


these two uptimes are not the same thing, check apachectl fullstatus and you will see what i mean

**Comment by richardforth** [comment]
The error message wording is quite clear, we are not discussing server uptime (as in ubuntu) we are discussing apache uptime,

"apache has been restarted within the last 24 hours"

**Comment by richardforth** [comment]
```perl

	# Check 8
	# determine the Apache uptime
	our @apache_uptime = get_apache_uptime($pid);
	
	if ( ! $NOINFO ) { show_info_box(); print "Apache has been running ${CYAN}$apache_uptime[0]${ENDC}d ${CYAN}$apache_uptime[1]${ENDC}h ${CYAN}$apache_uptime[2]${ENDC}m ${CYAN}$apache_uptime[3]${ENDC}s.\n" }
	if ( $apache_uptime[0] == "0" ) { 
		if ( ! $NOWARN ) { 
			show_warn_box(); print "${RED}*** LOW UPTIME ***${ENDC}.\n"; 
			show_advisory_box(); print "${YELLOW}The following recommendations may be misleading - apache has been restarted within the last 24 hours.${ENDC}\n";
		}
	}

```

**Comment by richardforth** [comment]
```perl

# this will us ps to determine the Apache uptime. it returns an array 
sub get_apache_uptime {
	my ( $pid ) = @_;

	# this will return the running time for the given pid in the format 
	# "days-hours:minutes:seconds"
	my $uptime = `ps -eo \"\%p \%t\" | grep $pid | grep -v grep | awk \'{ print \$2 }\'`;
	chomp($uptime);

	print "VERBOSE: Raw uptime: $uptime\n" if $main::VERBOSE;

	# check to see if we've been running for multiple days
	my ($days, $hours, $minutes, $seconds);
	if ( $uptime =~ m/^.*-.*:.*:.*$/ ) {	
		$days = $uptime;
		$days =~ s/([0-9]*)-.*/$1/;

		# trim the days off of our uptime value
		$uptime =~ s/.*-(.*)/$1/;
	
		($hours, $minutes, $seconds) = split(':', $uptime);
	}
	elsif ( $uptime =~ m/^.*:.*:.*/ ) {
		$days = 0;
		($hours, $minutes, $seconds) = split(':', $uptime);
	}
	elsif ( $uptime =~ m/^.*:.*/) {
		$days = 0;
		$hours = 0;
		($minutes, $seconds) = split(':', $uptime);	
	}
	else {
		$days = 0;
		$hours = 0;
		$minutes = 00;
		$seconds = 00;
	}

	# push everything into an array to pass back
	my @apache_uptime = ( $days, $hours, $minutes, $seconds );

	

	return @apache_uptime;
}
```

**Comment by richardforth** [comment]
the screenshot of the pid, thats output shows

8-00:02:40

which shoudl be translated as 8 days, 0 hours, 2 minutes and 4 seconds right?

I have a feeling then, that apache has picked up the wrong PID file because of the $SUFFIX thing

can you confirm (without using apache2buudy) what the actual parent PID is? You may have to check for the actual pidfile, not what apache2buddy reports - as I beleive this is wrong, and its looking at a different PID altogether and giving you random results for some other program

**Comment by richardforth** [comment]
can you run `# ps auxfwww | grep 28185` for me please? 

also

`# ps auxfwww | grep apache2`

**Comment by richardforth** [comment]
Hi, the domain has gone down again, due to 123reg being crap

therefore can yu run this test for me as well:

```
# ps -eo "%p %t" | grep 4893 | grep -v grep | awk '{ print $2 }' && curl -sL https://raw.githubusercontent.com/richardforth/apache2buddy/master/apache2buddy.pl | perl | grep "been running"
20:52
[ INFO     ] Apache has been running 0d 0h 20m 53s.
```

I want to see what youre getting? Many Thanks

**Comment by richardforth** [comment]
also

```
# apache2ctl fullstatus | grep uptime
   Server uptime: 23 minutes 10 seconds
```

so full test with 3 command running almost ategther, (expect a second or two difference maybe:

```
# apache2ctl fullstatus | grep uptime  && ps -eo "%p %t" | grep 4893 | grep -v grep | awk '{ print $2 }' && curl -sL https://raw.githubusercontent.com/richardforth/apache2buddy/master/apache2buddy.pl | perl | grep "been running"
   Server uptime: 26 minutes 27 seconds
26:28
[ INFO     ] Apache has been running 0d 0h 26m 28s.
```

run apache2buddy last as it takes several seconds to complete, ther should only be 1 or 2 seconds out to account for the execution of the code.

**Comment by richardforth** [comment]
Again i just want to stress, though, when it says "Server uptime" its referring to apache server not "the server":

Illustration:

```
root@server-01:~# uptime
 19:28:31 up 43 min,  1 user,  load average: 0.00, 0.05, 0.06
root@server-01:~# apache2ctl fullstatus | grep uptime
   Server uptime: 33 minutes 30 seconds
root@server-01:~# service apache2 stop
 * Stopping web server apache2                                                                                                                                                                                                        *
root@server-01:~# service apache2 start
 * Starting web server apache2                                                                                                                                                                                                       AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 2001:4801:7823:76:be76:4eff:fe10:ad85. Set the 'ServerName' directive globally to suppress this message
 *
root@server-01:~# apache2ctl fullstatus | grep uptime
   Server uptime: 5 seconds
root@server-01:~# uptime
 19:29:18 up 43 min,  1 user,  load average: 0.00, 0.04, 0.06
root@server-01:~#
```

**Comment by richardforth** [comment]
Here is the code that I beleive is the problem:

```perl
			} elsif ($pidfile_cfv eq "/var/run/apache2/apache2\$SUFFIX.pid") {
				our $pidfile = "/var/run/apache2/apache2.pid";
			} elsif ($pidfile_cfv eq "/var/run/apache2\$SUFFIX.pid") {
				our $pidfile = "/var/run/apache2.pid";

```

Note that apache2buddy CAN cull out apache configs, but CANNOT properly pull out and therefore make variable substitutions. Hence we are just guessing, this is a problem, definately a bug, but it seems at the moment to be an insurmountable one, so, yeah, thanks Ubuntu!

**Comment by richardforth** [comment]
Hi,

Just awaiting your test results, as I am not able to replicate this. I know its an issue though.

Kind Regards
Richard

**Comment by Oxicode** [comment]
Hola, disculpa la demora. Aquí los datos que me pediste. 

> can you run # ps auxfwww | grep 28185 for me please?
![image](https://cloud.githubusercontent.com/assets/1320709/22663541/fbb243fa-ec7a-11e6-95bc-d4a63ed50c30.png)


> ps auxfwww | grep apache2
![image](https://cloud.githubusercontent.com/assets/1320709/22663529/ef5cc440-ec7a-11e6-84d9-9717ea9bf727.png)

>apache2ctl fullstatus | grep uptime
![image](https://cloud.githubusercontent.com/assets/1320709/22663598/33228390-ec7b-11e6-89ee-4aae04ea6a32.png)

**Comment by richardforth** [comment]
As a final test for me, can you run the following:

apache2ctl fullstatus | grep uptime

curl -sL apache2buddy.pl | perl | grep "been running"

**Comment by Oxicode** [comment]
of course 

![image](https://cloud.githubusercontent.com/assets/1320709/22667067/1c99887c-ec89-11e6-9022-c78a90471a5b.png)

**Comment by richardforth** [comment]
These two uptimes  should match....

Hmm.

I don't know what to say as I am not able to replicate this behaviour

Can you run this again but also include the ps oe command from your first
update? All three should be the same. This is what I get when I try. (See
my previous tests).

**Comment by Oxicode** [comment]
![image](https://cloud.githubusercontent.com/assets/1320709/22670359/c961bb58-ec96-11e6-833b-5d81aa29d505.png)

**Comment by Oxicode** [comment]
Voy a reiniciar mi servidor para ejecutar los test mañana por la noche

**Comment by richardforth** [comment]
Thank you

I will await your result tomorrow night

Here's what I see so far

1. Apachectl and the ps oe output definitely match.

2. Apache2buddy is not displaying the correct uptime this makes me think
apache2buddy isnt looking at the right pid. Sines al, it does is read the
pid run time ( in the same way that apchectl does:

For example:

8-11:02:03

Would be translated into 8 days, 11 hours, 2 minutes, and 3 seconds.

Restarting the server might help. Renmember though ubuntu
 Uptime is not the same as apache uptime.

The problem here is between the uptime according to ps oe and the
apache2buddy.pl uptime report

It might also be worth checking out exactly where the pid file is as I have
a feeling that we are either looking at the wrong pid or there's something
odd going on in your case.

Looking forward to seeing the results.

**Comment by richardforth** [comment]
Hi Oxicode,

can you also find out for me which is the REAL pidfile?  I have a real feeling apache2buddy is picking up the wrong one.


can you also run:

```
apache2ctl fullstatus | grep uptime

curl -sL apache2buddy.pl | perl | egrep -i "parent pid|been running"

```

and then the ps -eo command on the parent pid that it reports? 

Also if you can find the real pidfile without using apache2buddy to verify we are picking up the right file, as the uptime is a direct conversion from the ps -oe output....

...this is very strange, Im hoping that the restart fixed it

**Comment by Oxicode** [comment]
![image](https://cloud.githubusercontent.com/assets/1320709/22741301/bc3bb2e4-ede0-11e6-8952-72b36a4544c2.png)

**Comment by richardforth** [comment]
Perfect 👌 looks like the reboot solved it :)

**Comment by Oxicode** [comment]
lol, hahaha
Igual la próxima semana voy a darle una mirada más para descartar cualquier eventualidad.
crearé un ticket nuevo si pasa algo.

**Comment by richardforth** [comment]
Any time I'm always willing to look into bugs. In this case I think
something wierd was going on there that I really can't explain. I may have
to look at adding additional debug (verbose) lines if it happens again.
Very odd. Anyway glad it's all sorted. :)
