### ISSUE TITLE
Unable to get list of PIDs

### ISSUE THREAD

**Issue by jrhutchins** [richardforth/apache2buddy#19]
RHEL 6.8, Apache -2.2.15, PHP 5.3.3

Analyzing apache memory use...
[ INFO     ] httpd is currently using 3087.04 MB of memory.
[ CRITICAL ] Error getting a list of PIDs
DEBUG -> Process Name: /usr/sbin/httpd
DEBUG -> Apache_user: http-we+
DEBUG -> Search Type: high

**Comment by richardforth** [comment]
Hi, can you please get a verbose output for me?

# curl -sL apache2buddy.pl | perl - --verbose

**Comment by richardforth** [comment]
I'm suspecting you're running apache as a custom user and not "apache".

**Comment by richardforth** [comment]
The thing is that plus symbol you see:
`DEBUG -> Apache_user: http-we+`

I think what is happening is apache2buddy is trying to find all the pids belonging to a user with a longer name than fits on the output of some other process, like 'ps' so it cant find anything, and gives a null listing.

You need to revert back to 'apache', its not something I can fix in my code as its reliant upon the output of other programs. If that makes sense.

in essense, the username is too long to be displayed in full and is shortened to 'http-we+' which is an invalid user. A full verbose output will confirm this. And you'll be able to replicate it by looking for apache processes and checking the user column.

**Comment by richardforth** [comment]
Code block concerned:

```sub get_memory_usage {
	my ($process_name, $apache_user, $search_type) = @_;
	
	my (@proc_mem_usages, $result);

	# get a list of the pid's for apache running as the appropriate user
	my @pids = `ps aux | grep $process_name | grep -v root | grep $apache_user | awk \'{ print \$2 }\'`;

        # if length of @pids is still zero then die with an error.
	if (@pids == 0) {
                show_crit_box(); print ("Error getting a list of PIDs\n");
		print ("DEBUG -> Process Name: ".$process_name."\nDEBUG -> Apache_user: ".$apache_user."\nDEBUG -> Search Type: ".$search_type."\n\n");
		exit 1;
	} ```

**Comment by jrhutchins** [comment]
On Tue, November 15, 2016 10:36 am, Richard Forth wrote:
> I'm suspecting you're running apache as a custom user and not "apache".

Correct, http-web is the user.  Curiously, I get no output from the curl
command you requested, but here is the output from running a local copy:

Performing Auto-Discovery, and Pre-Flight Checks...
[ OK       ] This script is being run as root.
[ OK       ] The utility 'pmap' exists and is available for use:
/usr/bin/pmap
[ OK       ] 'php' exists and is available for use: /usr/bin/php

[ OK       ] The port (port 80) is a valid port.
[ INFO     ] We are attempting to discover the operating system type and
version number ...
[ INFO     ] OS Name: Red Hat Enterprise Linux
[ INFO     ] OS Release: 6.8
[ OK       ] Apache2buddy supports this OS Release/Version.
[ INFO     ] Hostname: txgov4svwppweb1
[ INFO     ] Primary IP: 168.58.226.200
[ INFO     ] We are checking the service running on port 80...
[ INFO     ] The process listening on port 80 is /usr/sbin/httpd
[ INFO     ] The process running on port 80 is Apache/2.2.15 (Unix).
[ INFO     ] Apache has been running 0d 0h 44m 54s.
[ INFO     ] The full path to the Apache config file is:
/etc/httpd/conf/httpd.conf
[ INFO     ] Apache is using prefork model.
[ WARNING  ] Non-standard apache set-up, apache is running as UID: 52001
(http-web ). Expecting UID 48 ('apache' or 'www-data').
[ INFO     ] Apache runs as http-web .
[ INFO     ] pidfile setting is /var/run/httpd/httpd.pid.
[ INFO     ] Actual pidfile is /var/run/httpd/httpd.pid.
[ INFO     ] Parent PID: 2227.
[ OK       ] Memory usage of parent PID is less than 50MB: 6704 Kilobytes.
[ INFO     ] Your server has 3832 MB of PHYSICAL memory.
[ INFO     ] Your MaxClients setting is 512.
[ OK       ] Current Apache Process Count is 29, including the parent PID.
[ INFO     ] Your ServerLimit setting is 512.
[ INFO     ] Your MaxRequestsPerChild setting is 4000.

Detecting PHP Memory Limits...
[ INFO     ] Your PHP Memory Limit (Per-Process) is 1024 MB.

Detecting additional services for consideration...
[ INFO     ] Java Detected => Using 75.33 MB of memory.

Detecting If Maxclients or MaxRequestWorkers has been hit recently....

PRO TIP: If this process appears to hang, press CTRL + c to exit the
program, and then
go check for a large error log file in /var/log/httpd or /var/log/apache2.

[ WARNING  ] MaxClients has been hit recently (maximum of 5 results
shown), consider the dates and times below:
[Mon Nov 14 15:44:09 2016] [error] server reached MaxClients setting,
consider raising the MaxClients setting

Analyzing apache memory use...
[ INFO     ] httpd is currently using 1352.42 MB of memory.
[ CRITICAL ] Error getting a list of PIDs
DEBUG -> Process Name: /usr/sbin/httpd
DEBUG -> Apache_user: http-we+
DEBUG -> Search Type: high

**Comment by richardforth** [comment]
$apache_user is stored from prior execution tasks, and then this process does the following:

`# ps aux | grep $process_name | grep -v root | grep $apache_user | awk '{ print $2 }'`


replace $process_name with /usr/sbin/httpd

replace $apache_user with the FULL username.

You should get the list of PIDs no problem

however if you do:

replace $apache_user with "http-we+" which is the output from a previous function

```
	# Check 13	
	# get the entire config, including included files, into an array
	our @config_array = build_config_array($full_apache_conf_file_path,$apache_root);
	# determine what user apache runs as 
	our $apache_user = find_master_value(\@config_array, $model, 'user');
        # account for 'apache\x{d}' strangeness
        $apache_user =~ s/\x{d}//;
	unless ($apache_user eq "apache" or $apache_user eq "www-data") {
                my $apache_userid = `id -u $apache_user`;
                chomp($apache_userid);
                # account for 'apache\x{d}' strangeness
                $apache_user =~ s/\x{d}//;
                show_warn_box(); print ("${RED}Non-standard apache set-up, apache is running as UID: ${CYAN}$apache_userid${RED} (${CYAN}$apache_user${RED}). Expecting UID 48 ('apache' or 'www-data').${ENDC}\n");
		if ( ! $NOINFO ) { show_info_box(); print "Apache runs as ${CYAN}$apache_user${ENDC}.\n" }
        }	
	
	if (length($apache_user) > 8) {
		# Now we have to keep the first 7 characters and change the 8th character to a + sign, eg 'developer' becomes 'develop+'
		my $original_user = $apache_user;
		$apache_user = substr($original_user, 0, 7)."+";
	}```


So its this code that does it. this fixed a previous bug of the same nature.

can you please run the 'ps' command and let em know how your user is displaying? Apparently the Check13 fix should have addressed this issue. so I'm interested to see why its not working out as we expect.


`ps auxfwww | grep httpd`

**Comment by richardforth** [comment]
Ive also responded as i found some code responsible for the + sign.

Would you be able to get me the output from:

`ps auxfwww | grep httpd`

**Comment by richardforth** [comment]
Hi, i know Im updating faster than youre replying, so I'm kinfd of paraphrasing previous responses as they all relate:

So you see here:

`[ WARNING  ] Non-standard apache set-up, apache is running as UID: 52001
(http-web ). Expecting UID 48 ('apache' or 'www-data').` 

At this point we know the user is http-web.

There is code that changes this, to address a previous bug whereby long names were shortened to 7chars plus the plus-sign in ps output.

```
    # Check 13  
    # get the entire config, including included files, into an array
    our @config_array = build_config_array($full_apache_conf_file_path,$apache_root);
    # determine what user apache runs as 
    our $apache_user = find_master_value(\@config_array, $model, 'user');
        # account for 'apache\x{d}' strangeness
        $apache_user =~ s/\x{d}//;
    unless ($apache_user eq "apache" or $apache_user eq "www-data") {
                my $apache_userid = `id -u $apache_user`;
                chomp($apache_userid);
                # account for 'apache\x{d}' strangeness
                $apache_user =~ s/\x{d}//;
                show_warn_box(); print ("${RED}Non-standard apache set-up, apache is running as UID: ${CYAN}$apache_userid${RED} (${CYAN}$apache_user${RED}). Expecting UID 48 ('apache' or 'www-data').${ENDC}\n");
        if ( ! $NOINFO ) { show_info_box(); print "Apache runs as ${CYAN}$apache_user${ENDC}.\n" }
        }   

    if (length($apache_user) > 8) {
        # Now we have to keep the first 7 characters and change the 8th character to a + sign, eg 'developer' becomes 'develop+'
        my $original_user = $apache_user;
        $apache_user = substr($original_user, 0, 7)."+";
    }
```
 

So now we have $original_user = http-web
And we now have $apache_user = http-we+


Later in the show, when we get a list of PIDS, its running this code:

`# ps aux | grep /usr/sbin/httpd | grep -v root | grep http-we+ | awk '{ print $2 }'`

can you please try a few variants of this command and tell me what works for you.

The previous fix should mean this returns some results, however, its probably going to be http-web not http-we+

Interestingly:

`if (length($apache_user) > 8) {`

In theory, this should return false, as 'http-web' is exactly 8 chars, not greater than 8 chars. So a fix may still be possible.

This issue only ever arises when you have a custom username for apache though.

**Comment by jrhutchins** [comment]
On Tue, November 15, 2016 10:56 am, Richard Forth wrote:
> Ive also responded as i found some code responsible for the + sign.
>
> Would you be able to get me the output from:
>
> `ps auxfwww | grep httpd`

 ps auxfwww | grep httpd
root      3929  0.0  0.0 103320   828 pts/0    S+   11:11   0:00          
               \_ grep httpd
root      2227  0.0  0.3 498740 11788 ?        Ss   10:05   0:00
/usr/sbin/httpd
http-web  2229  0.0  0.1 500888  7396 ?        S    10:05   0:00  \_
/usr/sbin/httpd
http-web  3698  1.0  1.9 515664 77168 ?        S    11:01   0:06  \_
/usr/sbin/httpd
http-web  3729  0.8  1.9 516404 78072 ?        S    11:01   0:05  \_
/usr/sbin/httpd
http-web  3834  0.5  1.3 515892 54636 ?        S    11:06   0:01  \_
/usr/sbin/httpd
http-web  3847  0.9  1.4 515984 55740 ?        R    11:07   0:02  \_
/usr/sbin/httpd
http-web  3854  0.5  1.4 516248 55860 ?        S    11:07   0:01  \_
/usr/sbin/httpd
http-web  3855  0.6  1.9 516520 77948 ?        S    11:07   0:01  \_
/usr/sbin/httpd
http-web  3863  0.7  1.5 517472 59804 ?        S    11:08   0:01  \_
/usr/sbin/httpd
http-web  3864  0.9  1.4 515480 55684 ?        S    11:08   0:01  \_
/usr/sbin/httpd
http-web  3866  0.7  1.4 516504 55912 ?        S    11:08   0:01  \_
/usr/sbin/httpd
http-web  3867  0.6  1.3 516100 54724 ?        S    11:08   0:01  \_
/usr/sbin/httpd
http-web  3868  0.5  1.4 516248 55024 ?        S    11:08   0:00  \_
/usr/sbin/httpd
http-web  3869  0.8  1.4 515472 55004 ?        S    11:08   0:01  \_
/usr/sbin/httpd
http-web  3870  1.1  1.4 516252 58060 ?        S    11:08   0:02  \_
/usr/sbin/httpd
http-web  3878  0.4  1.3 516264 54632 ?        S    11:08   0:00  \_
/usr/sbin/httpd
http-web  3879  0.7  1.3 514296 53784 ?        S    11:08   0:01  \_
/usr/sbin/httpd
http-web  3880  0.5  1.9 516520 77720 ?        S    11:08   0:00  \_
/usr/sbin/httpd
http-web  3883  0.6  1.3 515480 54316 ?        S    11:08   0:01  \_
/usr/sbin/httpd
http-web  3885  0.6  1.3 515796 54408 ?        S    11:08   0:01  \_
/usr/sbin/httpd
http-web  3892  1.3  1.4 515880 55676 ?        S    11:08   0:02  \_
/usr/sbin/httpd
http-web  3903  0.0  0.2 501312  8740 ?        S    11:10   0:00  \_
/usr/sbin/httpd
http-web  3904  1.1  1.3 516240 54820 ?        S    11:10   0:00  \_
/usr/sbin/httpd
http-web  3905  0.1  1.3 516352 51892 ?        S    11:10   0:00  \_
/usr/sbin/httpd
http-web  3907  0.6  1.3 516100 54608 ?        S    11:10   0:00  \_
/usr/sbin/httpd
http-web  3909  0.8  1.3 515340 54220 ?        S    11:10   0:00  \_
/usr/sbin/httpd
http-web  3910  1.0  1.3 516264 54508 ?        S    11:10   0:00  \_
/usr/sbin/httpd
http-web  3911  0.7  1.3 516240 54516 ?        S    11:10   0:00  \_
/usr/sbin/httpd
http-web  3912  0.7  0.0      0     0 ?        Z    11:10   0:00  \_
[httpd] <defunct>
http-web  3913  0.6  1.3 516248 54516 ?        S    11:10   0:00  \_
/usr/sbin/httpd
http-web  3919  0.0  0.2 501312  8652 ?        S    11:11   0:00  \_
/usr/sbin/httpd
http-web  3920  0.0  0.2 501312  8652 ?        S    11:11   0:00  \_
/usr/sbin/httpd
http-web  3921  0.5  1.3 516360 51888 ?        S    11:11   0:00  \_
/usr/sbin/httpd
http-web  3922  3.2  1.3 515472 54056 ?        S    11:11   0:00  \_
/usr/sbin/httpd
http-web  3923  1.1  1.3 515728 51456 ?        S    11:11   0:00  \_
/usr/sbin/httpd
http-web  3924  1.5  1.2 514296 49092 ?        S    11:11   0:00  \_
/usr/sbin/httpd
http-web  3925  0.0  0.2 501312  8644 ?        S    11:11   0:00  \_
/usr/sbin/httpd

**Comment by richardforth** [comment]
Ok I cracked it, I made a breakthrough I think

`[ WARNING ] Non-standard apache set-up, apache is running as UID: 52001 (http-web ). Expecting UID 48 ('apache' or 'www-data').``

If you look closely, it seems that the 'http-web ' user has a space in it, an the very end, so its being picked up as 9 chars, not 8 chars.

I thought about this because www-data (on ubuntu systems) is exactly 8 chars, and we dont see this problem arising there.

**Comment by richardforth** [comment]
cool, thanks for the update. I will see what I can do

**Comment by jrhutchins** [comment]
> `# ps aux | grep /usr/sbin/httpd | grep -v root | grep http-we+ | awk '{
> print $2 }'`

As expected http-we+ returns null, http-web returns a list of PIDs.

**Comment by jrhutchins** [comment]
Replacing $apache_user with http-web in the PID search code allows the
program to complete successfully.

**Comment by jrhutchins** [comment]
On Tue, November 15, 2016 11:14 am, Richard Forth wrote:
> Ok I cracked it, I made a breakthrough I think
>
> `[ WARNING ] Non-standard apache set-up, apache is running as UID: 52001
> (http-web ). Expecting UID 48 ('apache' or 'www-data').``
>
> If you look closely, it seems that the 'http-web ' user has a space in it,
> an the very end, so its being picked up as 9 chars, not 8 chars.
>
> I thought about this because www-data (on ubuntu systems) is exactly 8
> chars, and we dont see this problem arising there.

I thought it might be something like that.  I'll check the user.  This
configuration was very unconventional, the user was not created with the
usual tools but by echoing a string to the passwd file, mostl likely using
Windows.

**Comment by richardforth** [comment]
Yeah cool I saw that, I also spotted WHY your username is being shortened to http-we+, its because theres a hidden space (notice how the right bracket is off by a space in the output?).

We have 2 possible ways to fix this:

1. Recommended - you try to have the configuration amended by removing the erroneous space character.

2. I can try and change my 'if' block  from

 `if (length($apache_user) > 8) {`

to

`if (length($apache_user) > 9) {`

and HOPE it doenst break other executions.

I suspect if I do number 2. then other people might complain. Let me know your thoughts? Could you check if there is indeed an extra space in your apache config?

**Comment by jrhutchins** [comment]
The space is coming from httpd.conf - the User http-web line has a space
at the  end.

**Comment by richardforth** [comment]
thanks for that

for now hard coding the user is and running apache2buddy locally might be your best answer, until you can get approval to change the config, as Ive not had any problems with this for a couple of years now so i'm loathe to update the code as this seems like an edge case, and "fixing it" might break how others experience it. You see that extrs space made all the difference because it makes the 

`if (length($apache_user) > 8) {`

return True, not False.

Would you agree with this solution and happy for me to close?

**Comment by jrhutchins** [comment]
Please don't update your code for an error in my configuration unless you
think it has broader application in the future.  I really appreciate your
help in troubleshooting this, you've gone quite above and beyond.

**Comment by richardforth** [comment]
Thanks jrhutchins

Its my pleasure, in closing, i just wanted to provide insight into the Check13 fix:

In essense, a string that is eight chars or less will display correctly in ps output, if a string is longer than 8 chars, ps changes it to a 7char string plus the plus symbol (+). to say "there are more chars than I could display" so I had to mimic that behaviour to fix a similar bug whereby apahe2budy is doing a search for 

`reallylongusername` 

in ps. yet the displayed chars were

`reallyl+`



for a total of 8 chars, resulting in a null list. Hence the inception of "Check 13" in the code. The comments in code explain what is being done and why:


```    if (length($apache_user) > 8) {
        # Now we have to keep the first 7 characters and change the 8th character to a + sign, eg 'developer' becomes 'develop+'
        my $original_user = $apache_user;
        $apache_user = substr($original_user, 0, 7)."+";
    }```


Because of the extra space character in your case, apache2buddy is detecting it as a nice character string, and thus making a modification to the string which is not reflected in 'ps'. for some reason. 

That's the only bit that is confusing me, is why ps isnt behaving the same way, in which case you wouldnt have the issue you reported. unless of course ps "strips" the username so that any leading or trailing whitespace dont count (when it should).

So theres two places you'll need to apply the fix:

1. in /etc/passwd 

2. in your httpd.conf file

plus anywhere else the apache user is mentioned, like /etc/group

I think in this case it is appropriate to leave the code alone and address this in your configuration.

I'm always happy to help.

Thanks for the bug report though :) 

Kind Regards
Richard

**Comment by jrhutchins** [comment]
On Tue, November 15, 2016 11:38 am, Richard Forth wrote:
> That's the only bit that is confusing me, is why ps isnt behaving the same
> way, in which case you wouldnt have the issue you reported. unless of
> course ps "strips" the username so that any leading or trailing whitespace
> dont count (when it should).
>
> So theres two places you'll need to apply the fix:
>
> 1. in /etc/passwd
>
> 2. in your httpd.conf file
>
> plus anywhere else the apache user is mentioned, like /etc/group

I think what's happening is that the username is correct in /etc/passwd
and /etc/group, and that the system is actually using the correct name
(including in ps), but that your script is pulling the name + space from
the config file and using that.

**Comment by jrhutchins** [comment]
I tested my theory that the script was picking up the space by removing
the space and running the original script, it worked.

I'm not sure I understand the use of the + appended to the user name - a
partial user name should match, so you should be able to just truncate.

**Comment by richardforth** [comment]
Ah OK I got you.

I'll add a fix then to strip the trailing spaces if picked up in the config.

Thanks again.

**Comment by richardforth** [comment]
Hi,

A fix has gone live now. 

code:

`$apache_user =~ s/^\s*(.*?)\s*$/$1/; # address issue #18, strip whitespace from both sides.`

If youre able to test and let me know, although I understand youve already fixed your config, let me know either way and I'll close this out properly.

Cheers again for the testing!

**Comment by richardforth** [comment]
I tested this locally and it seems to do the trick, let me know if youre able to test.

**Comment by jrhutchins** [comment]
On Tue, November 15, 2016 3:19 pm, Richard Forth wrote:
> I tested this locally and it seems to do the trick, let me know if youre
> able to test.

Verified that the new code works as expected with a space appended to the
user definition in httpd.conf.

**Comment by richardforth** [comment]
Excellent.

Have a great evening sir.

Closing issue #18

**Comment by richardforth** [comment]
Sorry issue #19. Not 18. I'll update the comments and the changelogs tomorrow.
