### ISSUE TITLE
Out of memory Issue

### ISSUE THREAD

**Issue by u-Map** [richardforth/apache2buddy#196]
Hi,
Script halts with 'Out of Memory !' error. Actually "server memory" has not ran out. Ulimit settings are also look fine to me.

Any idea?

[root@online umap]# ./apachebuddy.pl 
###########################################################
apache2buddy.pl report for
###########################################################
[ OK ] This script is being run as root.
[ OK ] The utility 'pmap' exists and is available for use: /usr/bin/pmap
[ OK ] The utility 'netstat' exists and is available for use: /bin/netstat
[ OK ] 'php' exists and is available for use: /usr/bin/php
[ OK ] The utility 'apachectl' exists and is available for use: /usr/sbin/apachectl
[ OK ] The port (port 80) is a valid port.
[ -- ] We are attempting to discover the operating system type and version number ...
[ -- ] Distro: Red Hat Enterprise Linux Server
[ -- ] Version: 6.0
[ -- ] Codename: Santiago
[ @@ ] New OS/Version verification checks are being worked on, you may get errors and teething problems. 02-04-2017
[ @@ ] Apologies for any inconvenience, this message will disappear when all issues resolved. 02-04-2017
[ OK ] This distro is supported by apache2buddy.pl.
[ -- ] Hostname: 
[ -- ] Primary IP: 
[ -- ] We are checking the service running on port 80...
[ -- ] The process listening on port 80 is /usr/sbin/httpd
[ -- ] The process running on port 80 is Apache/2.2.15 (Unix).
[ -- ] Apache has been running 0d 13h 49m 05s.
[ !! ] *** LOW UPTIME ***.
[ @@ ] The following recommendations may be misleading - apache has been restarted within the last 24 hours.
[ -- ] The full path to the Apache config file is: /etc/httpd/conf/httpd.conf
[ -- ] Apache is using prefork model.
[ -- ] pidfile setting is run/httpd.pid.
[ -- ] Actual pidfile is /var/run/httpd/httpd.pid.
[ -- ] Parent PID: 26088.
[ OK ] Memory usage of parent PID is less than 50MB: 18148 Kilobytes.
[ -- ] Your server has 15599 MB of PHYSICAL memory.
[ -- ] Your ServerLimit setting is 256.
[ -- ] Your MaxClients setting is 256.
[ OK ] Current Apache Process Count is 10, including the parent PID.
[ -- ] Number of vhosts detected: 1.
[ -- ]             |________ of which 1 are HTTP (specifically, port 80).
[ OK ] Current Apache vHost Count is less than maxclients.
[ -- ] Your MaxRequestsPerChild setting is 4000.
[ -- ] This server is NOT running Plesk.
[ -- ] This server is NOT running cPanel.
PHP Deprecated:  Comments starting with '#' are deprecated in /etc/php.ini on line 432 in Unknown on line 0
[ -- ] Your PHP Memory Limit (Per-Process) is 128 MB.
[ -- ] MySQL Detected => Using 24.59 MB of memory.
[ -- ] Java Detected => Using 37.48 MB of memory.

[ !! ] /var/log/httpd/ssl_error_log-20170604.gz --> 1.57GB
[ !! ] /var/log/httpd/ssl_error_log-20170603.gz --> 1.54GB
[ !! ] /var/log/httpd/ssl_error_log-20170606 --> 3.62GB
[ !! ] /var/log/httpd/ssl_error_log-20170601.gz --> 1.58GB
[ !! ] /var/log/httpd/ssl_error_log-20170602.gz --> 1.61GB
[ !! ] /var/log/httpd/ssl_error_log-20170605.gz --> 1.59GB
[ @@ ] Consider setting up a log rotation policy.
[ @@ ] Note: Log rotation should already be set up under normal circumstances, so very
[ @@ ] Large error logs can indicate a fundmental issue with the website / web application.
[ OK ] MaxClients has not been hit recently.
Out of memory!

[root@online umap]# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 124695
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1024
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

Thanks.

**Comment by richardforth** [comment]
The out of memory error is not an error coming from my script. Sorry

**Comment by richardforth** [comment]
To clarify, teh only memory messages I have in my scrips look like this:

```perl

	if ($memory_remaining < 0) {
		show_crit_box(); print "${RED}ERROR: Memory Overload Error: Remaining RAM in negative numbers! Dumping memory report, and exiting...${ENDC}\n";
		print "Available Mem: $available_mem\n";
		print "----------------------------------------------\n";
		print "Mysql Mem: $mysql_memory_usage_mbytes\n";
		print "Java Mem: $java_memory_usage_mbytes\n";
		print "Redis Mem: $redis_memory_usage_mbytes\n";
		print "Memcache Mem: $memcache_memory_usage_mbytes\n";
		print "Varnish Mem: $varnish_memory_usage_mbytes\n";
		print "PHP-FPM Mem: $phpfpm_memory_usage_mbytes\n";
		print "Gluster Mem: $gluster_memory_usage_mbytes\n";	
		print "----------------------------------------------\n";
		print "Remaining Mem: $memory_remaining\n";	
		exit;
	}
```

so the "Out of memory!" message you see there, was not generated by my script. Hence i cant say what or why you got that, i scanned the entire file and couldn't see that string or anything related to it. 

My best answer for you is that if you look at this code:

```perl

	# Check 19 : Maxclients Hits
	# This has been abstracted out into a separate subroutine
	if ( ! $SKIPMAXCLIENTS ) { 
		detect_maxclients_hits($model, $process_name) 
	} else {
		if ( ! $NOINFO ) { show_advisory_box(); print "Skipping Maxclients Hits check.\n" }
	}

	# Check 20 : PHP Fatal Errors
	# This has been abstracted out into a separate subroutine
	# This addresses issue #6 'Check for and report on PHP Fatal Errors in the logs'
	if ( ! $SKIPPHPFATAL ) {
		if ($PHP) {
			detect_php_fatal_errors($model, $process_name);
		}
	} else {
		if ( ! $NOINFO ) { show_advisory_box(); print "Skipping PHP FATAL Errors check.\n" }
	}
```

You will see that after the check for maxclients beign hit, it starts working on log files checking for php fatal errors, some of those logs are pretty big, obviously we know you have 16GB of RAM, but we don't know how much is currently in use, scanning large logs could have tipped it over the edge, obviously when the scripts aborted the ram would have freed itself up. So that's why you might not have seen it after the fact,

**Comment by u-Map** [comment]
>>scanning large logs could have tipped it over the edge

Yes. That was the case. Once logs removed, error disappeared.
