### ISSUE TITLE
Error PHP Memory Limits

### ISSUE THREAD

**Issue by Oxicode** [richardforth/apache2buddy#22]
![image](https://cloud.githubusercontent.com/assets/1320709/20839217/c0ba6050-b879-11e6-856d-2fa67e47d5ee.png)

**Comment by richardforth** [comment]
Hi,

That's not an error, it's your setting in php. -1 means unlimited.

**Comment by richardforth** [comment]
Next code release I will determine if it is -1 and then put in brackets (unlimited). 

As I say this isn't actually an error it's just reporting the memory limit as set in your php.ini

**Comment by Oxicode** [comment]
Vale. Gracias.

**Comment by richardforth** [comment]
```
sub detect_php_memory_limit {
        if ( ! $NOINFO) {
                print "\n${PURPLE}Detecting PHP Memory Limits...${ENDC}\n";

                our $apache_proc_php = get_php_setting('/usr/bin/php', 'memory_limit');
                show_info_box(); print "Your PHP Memory Limit (Per-Process) is ${CYAN}".$apache_proc_php." MB${ENDC}.\n";
        }
}
```


This is  the code block tha pulls in the memory limit directly from php.ini

**Comment by richardforth** [comment]
Modified this function ass follows:

```
sub detect_php_memory_limit {
        if ( ! $NOINFO) {
                print "\n${PURPLE}Detecting PHP Memory Limits...${ENDC}\n";

                our $apache_proc_php = get_php_setting('/usr/bin/php', 'memory_limit');
                show_info_box(); print "Your PHP Memory Limit (Per-Process) is ${CYAN}".$apache_proc_php." MB${ENDC}.\n";
                if ($apache_proc_php eq "-1") {
                        show_advisory_box(); print "You should set a PHP Memory Limit (-1 is ${CYAN}UNLIMITED${ENDC}) which is not reccommended.\n";
                }
        }
}
``

which produces the following output ONLY when php memory limit is set to '-1':

```
Detecting PHP Memory Limits...
[ INFO     ] Your PHP Memory Limit (Per-Process) is -1 MB.
[ ADVISORY ] You should set a PHP Memory Limit (-1 is UNLIMITED) which is not recommended.
````

Otherwise:

```
Detecting PHP Memory Limits...
[ INFO     ] Your PHP Memory Limit (Per-Process) is 128 MB.

```

**Comment by richardforth** [comment]
Changes pushed to staging.

**Comment by richardforth** [comment]
![image](https://cloud.githubusercontent.com/assets/5919831/20878460/03e6527c-bac7-11e6-929e-3489ff4d1f00.png)

This is what the "fix" looks like, as I said previously, its not a calculating error, it literally just pulls in the exact setting from php.ini. 

In an ideal world, you'd have this at the default of 128MB, however I know some devs just turn off the limit by setting this to "-1MB", Ive added code that detects this and reports an advisory.

The change is currently in the staging branch and should be pushed live as soon as I have completed testing.

**Comment by richardforth** [comment]
changes pushed to live (master).
