### ISSUE TITLE
Cloud Linux Support

### ISSUE THREAD

**Issue by TheSkyHeart** [richardforth/apache2buddy#226]
Hi,

could you please add Cloud Linux Support:

[ -- ] We are attempting to discover the operating system type and version number ...
[ -- ] Distro: CloudLinux Server
[ -- ] Version: 6.9
[ -- ] Codename: Igor Volk
[ !! ] This distro is not supported by apache2buddy.pl.
[ @@ ] Supported Distro's: 'Ubuntu', 'ubuntu', 'Debian', 'debian', 'Red Hat Enterprise Linux', 'Red Hat Enterprise Linux Server', 'redhat', 'CentOS Linux', 'CentOS', 'centos', 'Scientific Linux'.

**Comment by richardforth** [comment]
https://github.com/richardforth/apache2buddy/issues/26

Please see my closing comment there, thank you for your interest.

As a closing note, you are absolutely welcome and encouraged to fork this project and make your own version that supports CloudLinux. Please note the terms of the apache2.0 license apply to any derivative works.
