### ISSUE TITLE
PID Count

### ISSUE THREAD

**Issue by jrhutchins** [richardforth/apache2buddy#235]
I was able to add "Oracle Enterprise Linux" to the list of acceptable distributions.  This is on OEL 6.9.

The script was unable to get a PID count.  I suspect that this is because the PID file location is in the run/ folder under the ServerRoot, and possibly because this does not match the default setting in /etc/sysconfig/httpd.

**Comment by richardforth** [comment]
Hi that's great if you want to make a PR I'll try and merge it.

The only issue is that I don't have Oracle available for testing so it may
break in the future.

**Comment by jrhutchins** [comment]
I thought we'd had an issue with PID count before: https://github.com/richardforth/apache2buddy/issues/19
Different issue though.

Boy, this is really wierd.

VERBOSE: Searching Apache configuration for the user directive
VERBOSE: daemon
[ >> ] Non-standard apache set-up, apache is running as UID: 2 (daemon). Expecting UID 48 ('apache' or 'www-data').
[ -- ] Apache runs as daemon.
VERBOSE: Searching Apache configuration for the pidfile directive
VERBOSE: CONFIG NOT FOUND
[ -- ] pidfile setting is CONFIG NOT FOUND.
VERBOSE: Stripping any quotes from string ...
VERBOSE: BEFORE (CONFIG NOT FOUND).
VERBOSE: AFTER (CONFIG NOT FOUND).
VERBOSE: Looking for pid file ...
VERBOSE: Located pidfile at /var/run/httpd/httpd.pid.
[ -- ] Actual pidfile is /var/run/httpd/httpd.pid.
[ -- ] Parent PID: 2010.
[ OK ] Memory usage of parent PID is less than 50MB: 7056 Kilobytes.

User apache UID 48 exists, ps aux says httpd is running as apache.

ps aux | grep httpd| grep -v root | grep apache | awk '{ print $2 }'; 

returns 26 PIDs.

**Comment by richardforth** [comment]
Lol.

Not sure where to start here.

I'm going to make an assumption that apache2buddy.pl has picked up a config
file that apache is not using but has read in UID 2 from that and looked it
up in etc passwd as being 'daemon'.

This definitely works OK in standard red hat, CentOS and Ubuntu distros,
using the stock packages from the respective repositories.

**Comment by jrhutchins** [comment]
I'll keep digging.

We have some very strange non-standard practices left over from 
migrating sites from Solaris.

---
Jonathan

**Comment by jrhutchins** [comment]
It looks like most of the problem is quirks with variations of how OEL 
names/locates things.  I may see if I can get some time from one of our 
developers who groks perl to work out the differences, in which case I'll 
forward our findings.

Between the variations of OEL and the fact that this installation was 
basically copied (NFS was re-mounted) from Solaris 10, it's not surprizing 
that your script gets lost.

Thanks again for the effort and the responses.

--
Jonathan
--------------------------------------------

**Comment by richardforth** [comment]
You're welcome.

Hopefully this demonstrates why I keep a tight lid on supported
distributions.

I'm quite open to letting people fork my project and butchering it for
their own custom needs.

I'm wary of merging changes upstream that I can't test myself. So it may
mean that you go your own way with a new fork purely for your organisation.

You can do so with my blessing so long as you keep me in  the credits and
you abide by the spirit of the apache 2.0 license.

Hope that helps.
