### ISSUE TITLE
Unable to locate pmap

### ISSUE THREAD

**Issue by msaeedm** [richardforth/apache2buddy#238]
Hello,

I tried to run the script inside a jail in FreeNAS and I got the following error:
"Unable to locate the pmap utility. This script requires pmap to analyze Apache's memory consumption."
I searched pmap in pkgs and also in ports but could not find this utility.

Would you please give me suggestions to get pmap in order to run the script?

Thank you

**Comment by richardforth** [comment]
Basically don't run it in a jail, 

You kind of answered your own question there really. If you absolutely MUST run it in a jail you will need to make sure any binaries that apache2buddy is looking for  exist within the jail and are in the PATH.

Also FreeNAS is not supported so this would have most likely failed further down the line anyway. So I would advise you not to persue this further with FreeNAS.

the only supported distributions are.

Red Hat 6,7
CentOS 6,7
Ubuntu 14.04, 16.04
Debian 7, 8

There are no plans to support any additional distributions at this time.

**Comment by msaeedm** [comment]
Ah ok. Thank you. I suppose I will find out other ways/tools for Apache server optimization.
Thank you and keep up the good work!

**Comment by richardforth** [comment]
Thank you and sorry I wasn't able to assist.

apache2buddy seems to be the only tool out there (apart from the original script (apachebuddy.pl) however I beleive that also required pmap too,

You could of course download the sourcecode and hack it to bypass the OS checks but you'd need to get pmap (and a few other utilities) into the chroot  in order for this to work still , but as I dont do any testing on FreeNAS it may do very unpredicatable things.

As a one man band I dont have a lot or resources to throw at this so Im sticking to supporting only the main 4 linux distros used in production environments. 

Youre welcone to fork your own copy and try and make it work on FreeNAS but i wont be incorporating any changes upstream t support FreeNAS though. It comes with the apache 2.0 license. I just guess it depend how much like like to hack around with code :)

Sorry  wasnt able to help again
Rich
