### ISSUE TITLE
CloudLinux = Centos. Is not supported?

### ISSUE THREAD

**Issue by Akylenok** [richardforth/apache2buddy#258]
Hi. CloudLinux is an operating system based on Centos. Why is it not possible to analyze on the basis of CloudLinux? Maybe you can somehow force it to specify what to analyze as on Centos?

**Comment by richardforth** [comment]
I know its frustrating, but I dont have the ability to test on cloudlinux, the project is open sourced and licensed under apache 2.0 so youre welcome to fork and hack your won personal copy to work with Cloudlinux, I have no issues with that.

To answer your question I addressed this at length previously:
https://github.com/richardforth/apache2buddy/issues/26

Also these days I dont have much time to develop apache2buddy or fix the outstanding issues.
