### ISSUE TITLE
Any plans for Ubuntu 18.04 support?

### ISSUE THREAD

**Issue by markdwhite** [richardforth/apache2buddy#259]
It's recently gone 18.04.1 and I know I'm updating my production servers...

[ OK ] This distro is supported by apache2buddy.pl.                                                                                   
[ !! ] This distro version (18.04) is not supported by apache2buddy.pl.                                                               
[ @@ ] Supported Ubuntu (LTS ONLY) versions: '14.04', '16.04'.

Cheers,

**Comment by richardforth** [comment]
Hi yes I do plan to support LTS versions of Ubuntu but I haven't got around
to testing on 18.04 yet

**Comment by markdwhite** [comment]
Thanks for the reply. I'll check back in a few weeks then :)

**Comment by richardforth** [comment]
keeping this one open as it might be an easy kill, apologies for the lack of development time, I dont have the time I had a few years back to spend on this nowadays,

even if its not an easy kill it is still an issue that needs addressing as I had always planned to keep LTS versions supported (while they are in life). This is my bad.

**Comment by richardforth** [comment]
ubuntu 18.04 has python 3 but apache2buddy is looking for python or rather a 'python' binary:

```# curl -sL https://raw.githubusercontent.com/richardforth/apache2buddy/master/apache2buddy.pl | perl
######################################################
apache2buddy.pl report for XXXXXX   (YYY.YYY.YYY.YYY)
######################################################
[ OK ] This script is being run as root.
[ OK ] The utility 'pmap' exists and is available for use: /usr/bin/pmap
[ OK ] The utility 'netstat' exists and is available for use: /bin/netstat
[ OK ] 'php' exists and is available for use: /usr/bin/php
[ OK ] The utility 'apachectl' exists and is available for use: /usr/sbin/apachectl
[ !! ] Unable to locate the python binary. This script requires python to determine the Operating and Version.
[ -- ] To fix this make sure the python package is installed.
# py
py3clean             py3versions          pydoc3.6             pygettext3.6         pyjwt3               python3-jsondiff     python3-jsonpointer  python3.6            python3m
py3compile           pydoc3               pygettext3           pyhtmlizer3          python3              python3-jsonpatch    python3-jsonschema   python3.6m
# py
```

**Comment by richardforth** [comment]
looks like I had it hardcoded to 'python' within backticks:

# grep "python -c" apache2buddy.pl
        my $raw_platform = `python -c 'import platform ; print (platform.dist())'`;
        my $raw_platform = `python -c 'import platform ; print (platform.linux_distribution())'`;

need a way to somehow incorporate $python as a variable (that being python OR python3).

**Comment by richardforth** [comment]
testing with one liner

```bash
# perl -e '$python="python3"; $raw_platform = `$python -c "import platform ; print (platform.dist())"`; print "$raw_platform\n";'
('Ubuntu', '18.04', 'bionic')
```

**Comment by richardforth** [comment]
```perl

sub get_os_platform_older {
        our $python;
        my $raw_platform = `$python -c 'import platform ; print (platform.dist())'`;
        # ('CentOS Linux', '7.3.1611', 'Core')
        $raw_platform =~ s/[()']//g;
        my @platform = split(", ", $raw_platform);
        my $distro =  @platform[0];
        my $version = @platform[1];
        my $codename = @platform[2];
        return ($distro, $version, $codename);
}

sub get_os_platform {
        our $python;
        my $raw_platform = `$python -c 'import platform ; print (platform.linux_distribution())'`;
        # ('CentOS Linux', '7.3.1611', 'Core')
        $raw_platform =~ s/[()']//g;
        my @platform = split(", ", $raw_platform);
        my $distro =  @platform[0];
        my $version = @platform[1];
        my $codename = @platform[2];
        return ($distro, $version, $codename);
}

```

**Comment by richardforth** [comment]
oh its because of php 7.2 etc (currently Ive had to hard code in support for 7,0), will adjust.

**Comment by richardforth** [comment]
looks like I have a prototype working now on ubuntu 18.04

# perl apache2buddy.pl
######################################################
apache2buddy.pl report for XXXXXX (YYY.YYY.YYY.YYY)
######################################################
[ OK ] This script is being run as root.
[ OK ] The utility 'pmap' exists and is available for use: /usr/bin/pmap
[ OK ] The utility 'netstat' exists and is available for use: /bin/netstat
[ OK ] 'php' exists and is available for use: /usr/bin/php
[ OK ] The utility 'apachectl' exists and is available for use: /usr/sbin/apachectl
[ !! ] Unable to locate the python binary.
Trying for python3...
[ OK ] The 'python' binary exists and is available for use: /usr/bin/python3
[ OK ] The port (port 80) is a valid port.
[ -- ] We are attempting to discover the operating system type and version number ...
[ -- ] Distro: Ubuntu
[ -- ] Version: 18.04
[ -- ] Codename: bionic
[ OK ] This distro is supported by apache2buddy.pl.
[ OK ] This distro version is supported by apache2buddy.pl.
[ -- ] Hostname: XXXXXX
[ -- ] Primary IP: YYY.YYY.YYY.YYY
[ -- ] We are checking the service running on port 80...
[ -- ] The process listening on port 80 is /usr/sbin/apache2
[ -- ] The process running on port 80 is Apache/2.4.29 (Ubuntu).
[ -- ] The full path to the Apache config file is: /etc/apache2/apache2.conf
[ -- ] Apache is using prefork model.
[ -- ] pidfile setting is /var/run/apache2$SUFFIX/apache2.pid.
[ -- ] Actual pidfile is /var/run/apache2/apache2.pid.
[ -- ] Parent PID: 8510.
[ OK ] Memory usage of parent PID is less than 50MB: 5960 Kilobytes.
[ -- ] Apache has been running 0d 0h 55m 37s.
[ !! ] *** LOW UPTIME ***.
[ @@ ] The following recommendations may be misleading - apache has been restarted within the last 24 hours.
[ -- ] Your server has 979 MB of PHYSICAL memory.
[ >> ] ServerLimit directive not found, assuming default values.
[ -- ] Your ServerLimit setting is 256.
[ -- ] Your MaxRequestWorkers setting is 150.
[ OK ] Current Apache Process Count is 6, including the parent PID.
[ -- ] Number of vhosts detected: 0.
[ OK ] Current Apache vHost Count is less than maxrequestworkers.
[ @@ ] vHost Count works only when we have NameVirtualHosting enabled, check config manually, they may only have the default vhost.
[ >> ] MaxRequestsPerChild directive not found.
[ -- ] This server is NOT running Plesk.
[ -- ] This server is NOT running cPanel.
[ -- ] This server is NOT running Virtualmin.
[ -- ] Your PHP Memory Limit (Per-Process) is 128 MB.
[ OK ] No additional services were detected.
[ OK ] No large logs files were found in /var/log/apache2.
[ OK ] MaxClients has not been hit recently.
[ OK ] No PHP Fatal Errors were found.
[ OK ] No package updates found.
[ -- ] apache2 is currently using 73.11 MB of memory.
[ -- ] The smallest apache process is using 5.86 MB of memory
[ -- ] The average apache process is using 5.90 MB of memory
[ -- ] The largest apache process is using 6.09 MB of memory
[ OK ] Going by the average Apache process, Apache can potentially use 885.00 MB RAM:
                Without considering services: 90.40 % of total installed RAM
                Considering extra services: 90.40 % of remaining RAM
[ OK ] Going by the largest Apache process, Apache can potentially use 913.50 MB RAM:
                Without considering services: 93.31 % of total installed RAM
                Considering extra services: 93.31 % of remaining RAM


--------------------------------------------------------------------------------
### GENERAL FINDINGS & RECOMMENDATIONS ###
--------------------------------------------------------------------------------
Apache2buddy.pl report for server: XXXXXX (YYY.YYY.YYY.YYY):

Settings considered for this report:
[ !! ] *** LOW UPTIME ***.
[ @@ ] The following recommendations may be misleading - apache has been restarted within the last 24 hours.

        Your server's physical RAM:                                   979 MB
        Remaining Memory after other services considered:             979 MB
        Apache's MaxRequestWorkers directive:                         150      <--------- Current Setting
        Apache MPM Model:                                             prefork
        Largest Apache process (by memory):                           6 MB
[ OK ]  Your MaxRequestWorkers setting is within an acceptable range.
        Your recommended MaxRequestWorkers setting is between 144 and 160.     <------- Acceptable Range (10% of MAX)
        Max potential memory usage:                                   913 MB
        Percentage of TOTAL RAM allocated to Apache:                  93.31  %
        Percentage of REMAINING RAM allocated to Apache:              93.31  %
--------------------------------------------------------------------------------
A log file entry has been made in: /var/log/apache2buddy.log for future reference.

Last 5 entries:

2018/08/28 14:59:44 Model: "Prefork" Memory: "979 MB" MaxRequestWorkers: "150" Recommended: "160" Smallest: "5.86 MB" Avg: "5.90 MB" Largest: "6.09 MB" Highest Pct Remaining RAM: "93.31%" (93.31% TOTAL RAM)
2018/08/28 15:08:18 Model: "Prefork" Memory: "979 MB" MaxRequestWorkers: "150" Recommended: "160" Smallest: "5.86 MB" Avg: "5.90 MB" Largest: "6.09 MB" Highest Pct Remaining RAM: "93.31%" (93.31% TOTAL RAM)

#


I will need to put this in staging and then merge it into live. 

Stand by for further updates

**Comment by richardforth** [comment]
Looks like it working now, any issues on Ubuntu 18.04 feel free to log new issues :)

**Comment by markdwhite** [comment]
Still getting it. Full set of errors are:

    Use of uninitialized value $real_config in concatenation (.) or string at - line 1141 (#1)                                                                                                                
    Use of uninitialized value $result in substitution (s///) at - line 1172 (#1)                                                         
    Use of uninitialized value $apache_proc_php in concatenation (.) or string at - line 2237 (#1)

And for PHP:

    $ php -v                                                                                              
    PHP 7.2.7-0ubuntu0.18.04.2 (cli) (built: Jul  4 2018 16:55:24) ( NTS )                                                                
    Copyright (c) 1997-2018 The PHP Group                                                                                                 
    Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies with Zend OPcache v7.2.7-0ubuntu0.18.04.2, Copyright (c) 1999-2018, by Zend Technologies                                          
    $ php -i | grep "Configuration File"                                                                  
    Configuration File (php.ini) Path => /etc/php/7.2/cli                                                                                 
    Loaded Configuration File => /etc/php/7.2/cli/php.ini

Thanks

**Comment by richardforth** [comment]
can you run 

locate php.ini 

for me on your system?

Cheers

**Comment by markdwhite** [comment]
Sorry - that was the first thing I did this morning and I was clearly not as awake as I needed to be... And running FPM here, which was the only setup I tried from a clean install, so I'm not sure what this would look like on a system without php7.2-fpm.

    $ locate php.ini                                                                                      
    /etc/php/7.2/cli/php.ini                                                                                                              
    /etc/php/7.2/fpm/php.ini                                                                                                              
    /usr/lib/php/7.2/php.ini-development                                                                                                  
    /usr/lib/php/7.2/php.ini-production                                                                                                   
    /usr/lib/php/7.2/php.ini-production.cli

**Comment by richardforth** [comment]
nah thats cool, im used to red hat where everything is always just /etc/php.ini

try now, should be fixed

**Comment by markdwhite** [comment]
That's working now thanks! I'll have a play :)
