### ISSUE TITLE
Cloudlinux

### ISSUE THREAD

**Issue by tokelove** [richardforth/apache2buddy#267]
I've read the documentation and understand that Cloudlinux won't be supported, which is understandable. As it's essentially just a layer on top of Centos though running it should be fairly straight forward though if the script allowed it:

```
[ -- ] We are attempting to discover the operating system type and version number ...
[ -- ] Distro: CloudLinux
[ -- ] Version: 7.5
[ -- ] Codename: Viktor Gorbatko
[ !! ] This distro is not supported by apache2buddy.pl.
```

[From the wiki](https://github.com/richardforth/apache2buddy/wiki/CloudLinux)

> While upcoming changes "should" allow the script to run on CloudLinux, it will remain unsupported, due to lack of testing ability using this distro.

Any chance this could be allowed in the script?

**Comment by richardforth** [comment]
Hi,

Sorry no, I dont know what those "upcoming changes" were, wheni originally wrote that wiki page. It also said that CentOS 5 and RHEL 5 were supported, and theyy are EOL now, So I updated that wiki page.

By all means fork your own copy and tweak it as needed for CloudLinux, but I wont be accepting any PRs to support CloudLinux.

I will try and give you some useful pointers in the next few comments

**Comment by richardforth** [comment]
Line 327

```perl
	my @supported_os_list = ('Ubuntu',
				'ubuntu',
				'Debian',
				'debian',
				'Red Hat Enterprise Linux',
				'Red Hat Enterprise Linux Server',
				'redhat',
				'CentOS Linux',
				'CentOS',
				'centos',
				'Scientific Linux');
```

Line 346

```perl
	my @redhat_os_list = ('Red Hat Enterprise Linux', 'redhat', 'CentOS Linux', 'Scientific Linux');
```

Should be all you need to change  to get a local copy working on your cloudlinux server, but of course that just tricks apache2buddy.pl into proceeding further than the OS check, it may fail further down the line.

I hope that helps.

**Comment by richardforth** [comment]
I remembered what the "upcoming changes" were now, I did a load of pRs last night from staging and a new feature I have added is

`--skip-os-version-check` or `-O`

It may do unpredictable things but it will stop it moaning about things like Fedora and Cloudlinux etc not being supported and exiting prematurely.

Hope that helps.

**Comment by richardforth** [comment]
I will update the wiki as well
