### ISSUE TITLE
Cannot find apache config / $full_apache_conf_file_path uninitialized

### ISSUE THREAD

**Issue by dantman** [richardforth/apache2buddy#286]
I'm trying to run this script in a Docker container roughly based on the WordPress/php7.3-apache container, with net-tools+python3. But it's failing with this error:

```
######################################################################
apache2buddy.pl report for containername (ip)
######################################################################
[ OK ] This script is being run as root.
[ OK ] The utility 'pmap' exists and is available for use: /usr/bin/pmap
[ OK ] The utility 'netstat' exists and is available for use: /bin/netstat
[ OK ] 'php' exists and is available for use: /usr/local/bin/php
[ OK ] The utility 'apachectl' exists and is available for use: /usr/sbin/apachectl
[ !! ] Unable to locate the python binary.
Trying for python3...
[ OK ] The 'python' binary exists and is available for use: /usr/bin/python3
[ OK ] The port (port 80) is a valid port.
[ -- ] We are attempting to discover the operating system type and version number ...
[ -- ] Distro: debian
[ -- ] Version: 9.6
[ -- ] Codename:
[ OK ] This distro is supported by apache2buddy.pl.
[ OK ] This distro version is supported by apache2buddy.pl.
[ -- ] Hostname: container
[ -- ] Primary IP: ip
[ -- ] We are checking the service running on port 80...
[ -- ] The process listening on port 80 is apache2
[ -- ] The process running on port 80 is not Apache. Falling back to process list...
[ -- ] Apache is actually listening on port 80
[ -- ] The process running on port 80 is .
Use of uninitialized value $full_apache_conf_file_path in concatenation (.) or
        string at - line 1778 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.

    To help you figure out what was undefined, perl will try to tell you
    the name of the variable (if any) that was undefined.  In some cases
    it cannot do this, so it also tells you what operation you used the
    undefined value in.  Note, however, that perl optimizes your program
    and the operation displayed in the warning may not necessarily appear
    literally in your program.  For example, "that $foo" is usually
    optimized into "that " . $foo, and the warning will refer to the
    concatenation (.) operator, even though there is no . in
    your program.

[ !! ] Apache configuration file does not exist:
```

**Comment by mariojacobo** [comment]
+1 same error here. Debian 9 + PHP-FPM 7.2

**Comment by richardforth** [comment]
Hi thanks for raising this, but i wasnt able to replicate on a debian 9.6 installation:

```
...
[ -- ] We are attempting to discover the operating system type and version numbe
[ -- ] Distro: debian
[ -- ] Version: 9.6
[ -- ] Codename:

...

[ -- ] We are checking the service running on port 80...
[ -- ] The process listening on port 80 is /usr/sbin/apache2
[ -- ] The process running on port 80 is Apache/2.4.25 (Debian).
[ -- ] The full path to the Apache config file is: /etc/apache2/apache2.conf

```

apache2buddy only supports stock installations of apache

```bash
# apt-get install apache2
```

was all I ran before testing the script - FPM shouldnt  make any difference as we dont care about FPM - it fails much further back in the process anyway,

**Comment by richardforth** [comment]
looking at your outout more I think its the way your process identifies itself ans just apache2 rather than the full binary path like the stock install does,

Apache uses this to query apache for config file locations
https://github.com/richardforth/apache2buddy/blob/7dd27ae41f483eec32b065ce1678dd937df77018/apache2buddy.pl#L1025

example:

```perl
$apache_conf_file = `$process_name -V 2>&1 | grep \"SERVER_CONFIG_FILE\"`;
```

**Comment by dantman** [comment]
Would you consider supporting the common case I fall under? This is not a custom apache setup, I did not setup and configure Apache myself.

The image I am using is directly based on the official [_/php](https://hub.docker.com/_/php) (*#.#-apache*) docker image which is based on the official [_/httpd](https://hub.docker.com/_/httpd) (Apache HTTP Server) docker image.

This means that pretty much every single developer using docker locally, Kubernetes cluster, or other docker based server setup – will be unable to use apache2buddy.

**Comment by richardforth** [comment]
The only way I could support it is if you manage to get it to detect apache inside the docker container properly, currently its just detecting the executable as 'apache2' not the full path.

The stock installation detects it just fine.

**Comment by richardforth** [comment]
Apache2buddy wasnt really designed to be run in a docker container. If you manage to fix it I will be happy to consider merging a PR. I think however that they arent using a stock install of apache in that container, if they were it should be detected as normal.

**Comment by mariojacobo** [comment]
thank you for the quick feedback, yes we are running a similar setup to @dantman with Docker but debian stretch. I guess we can run the script in our local env, which is running full fledged VM. The reason why I wanted to run it inside the container, was to automate and adjust the image according to the hypervisor resources where it will be deployed.

**Comment by dantman** [comment]
Docker is using a compiled version of apache, not the debian package one. That is the case for most docker software. Using the OS version would lock containers to what is in OS package repositories. Make it impossible to have docker containers with different versions (e.g. an isolated container with a legacy version of php for an old application till you can update it). And make it impossible to update to the latest versions of software until it makes it into a package maintainer's cycle.

However the key thing is that while it's compiled, it's the same for everyone. So if we can find a way to detect the full path in this kind of environment and add it, it will work for everyone.

**Comment by richardforth** [comment]
Thanks for the update, however apache2buddy doesnt support custom installs which explains why it doesn't run in docker containers either.

I would recommend you fork this project and make changes according to your own custom needs. You have my blessing to do so, my only ask is that you retain the apache2.0 license and credits.

Sorry I wasnt able to help you on this occasion
