### ISSUE TITLE
Use of uninitialized value $_ in pattern match

### ISSUE THREAD

**Issue by kimusan** [richardforth/apache2buddy#303]
I ran the script directly from github today and got this error in the output:

```
[ OK ] No large log files were found in /var/log/apache2.
[ OK ] MaxClients has not been hit recently.
[ >> ] Apache only logs maxclients/maxrequestworkers hits once in a lifetime, if no restart has happened this event may have been rotated away.
[ >> ] As a backup check, please compare number of running apache processes (minus 1 for parent) against maxclients/maxrequestworkers.
[ >> ] For more information see https://github.com/apache/httpd/blob/0b61edca6cdda2737aa1d84a4526c5f9d2e23a8c/server/mpm/prefork/prefork.c#L809
[ OK ] No PHP Fatal Errors were found.
Use of uninitialized value $_ in pattern match (m//) at - line 2172 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.
    
    To help you figure out what was undefined, perl will try to tell you
    the name of the variable (if any) that was undefined.  In some cases
    it cannot do this, so it also tells you what operation you used the
    undefined value in.  Note, however, that perl optimizes your program
    and the operation displayed in the warning may not necessarily appear
    literally in your program.  For example, "that $foo" is usually
    optimized into "that " . $foo, and the warning will refer to the
    concatenation (.) operator, even though there is no . in
    your program.
    
[ -- ] apache2 is currently using 257.70 MB of memory.

```

Not sure what triggers it exactly.

Running on Ubuntu 16.04.6 LTS with all packages

**Comment by BartKoppers** [comment]
Had the same issue. 
After updating/upgrading Ubuntu 18 LTS, the 1st solution works (no errors anymore), however proposed 2nd option errors out:

> `root@1:~# cat /etc/issue`
> Ubuntu 18.04.3 LTS \n \l

> `root@1:~# apt-get update 2>&1 >/dev/null && dpkg --get-selections | xargs apt-cache policy | grep -1 Installed | sed -r 's/(:|Installed: |Candidate: )//' | uniq -u | tac | sed '/--/I,+1 d' | tac | sed '\$d' | sed -n 1~2p | egrep "^php|^apache2"`

> sed: -e expression #1, char 3: unterminated address regex

> `root@1:~# apt list coreutils sed grep`

>Listing... Done
> coreutils/bionic,now 8.28-1ubuntu1 amd64 [installed,automatic]
> grep/bionic-updates,now 3.1-2build1 amd64 [installed]
> sed/bionic,now 4.4-2 amd64 [installed,automatic]`

**Comment by richardforth** [comment]
Hi guys, 

Just popping my head in to say Hi, I havent forgotten this project or the issues, i am just pretty rammed for time, I appreciate all the feedback. 

Whats puzzling me is why its throwing the error in the first place, is it possible to run it in verbose mode for me (--verbose) and grab the output (if there is any) that might help debug that block of perl code I posted earlier that checks for updates?

If no joy, then leave it with me, I just dont have an Ubuntu machine to play with at the moment  - is it happening on every ubuntu 1604/1804 server or just a one off? 

Cheers guys.
Rich

**Comment by richardforth** [comment]
Hi,

In production at work I had the chance to run apache2buddy against a stock Ubuntu 18.04 server (running LAMP) and I wasnt able to replicate this issue.

**Comment by BartKoppers** [comment]
Can confirm that the apache2buddy.pl scripts works fine now.
(Minor issue is the mentioned "sed: -e expression #1, char 3: unterminated address regex" error in the manual method).
Can close.

**Comment by richardforth** [comment]
Thanks for confirming, though I havent made any changes so there was probably something wierd going on in the OS at the time.

Regarding the manual method, its possible that in order to get that to run properly in perl ther was some hidden escape characters that we dont need on the commandline:

sed: -e expression #1, char 3: unterminated address regex

I have a feeling its the "\$d" because perl might think $d is a variable? I would need to run som emore tests to be sure, but I think its fine.

Note that when I tested on a production boc runnign ubuntu 18 I didnt use any skip-updates options and it ran through without any issues. 

If it happens again if you can add the --verbose to get me some more information, that would be awesome. 

Otherwise i'll mark this as closed.
