### ISSUE TITLE
fix match "Error" message

### ISSUE THREAD

**Issue by wiechu** [richardforth/apache2buddy#312]
`$package_update =~ /Failed/ || /Error/`
means
`($package_update =~ /Failed/) || ($_ =~ /Error/)`

You dont't want it. Fix to:
`$package_update =~ /Failed|Error/`

**Comment by richardforth** [comment]
I wasnt able to replicate this as a problem:

```perl
$ vim failtest.pl
$ cat -n failtest.pl
     1  #!/usr/bin/perl
     2
     3  use strict;
     4  use warnings;
     5
     6  our $package_update = "Failed";
     7
     8  if ($package_update =~ /Failed/ || /Error/) {
     9    print "There was an error.\n";
    10  } else {
    11    print "OK.\n";
    12  }
    13
$ perl failtest.pl
There was an error.
```

**Comment by richardforth** [comment]
Sorry, I see what you mean:

```perl
$ vim failtest.pl
$ cat -n failtest.pl
     1  #!/usr/bin/perl
     2
     3  use strict;
     4  use warnings;
     5
     6  our $package_update = "Error";
     7
     8  if ($package_update =~ /Failed/ || /Error/) {
     9    print "There was an error.\n";
    10  } else {
    11    print "OK.\n";
    12  }
    13
$ perl failtest.pl
Use of uninitialized value $_ in pattern match (m//) at failtest.pl line 8.
OK.
$
```

**Comment by richardforth** [comment]
will hopefully get a fix in later today

**Comment by richardforth** [comment]
Good news is I fixed it in my test script:

```perl

$ vim failtest.pl
$ perl failtest.pl
There was an error.
$ cat -n failtest.pl
     1  #!/usr/bin/perl
     2
     3  use strict;
     4  use warnings;
     5
     6  our $package_update = "Error";
     7
     8  if ( $package_update !~ /Failed|Error/) {
     9    print "OK.\n";
    10  } else {
    11    print "There was an error.\n";
    12  }
    13
$ vim failtest.pl
$ cat -n failtest.pl
     1  #!/usr/bin/perl
     2
     3  use strict;
     4  use warnings;
     5
     6  our $package_update = "Failed";
     7
     8  if ( $package_update !~ /Failed|Error/) {
     9    print "OK.\n";
    10  } else {
    11    print "There was an error.\n";
    12  }
    13
$ perl failtest.pl
There was an error.
$ vim failtest.pl
$ cat -n failtest.pl
     1  #!/usr/bin/perl
     2
     3  use strict;
     4  use warnings;
     5
     6  our $package_update = "Wibble";
     7
     8  if ( $package_update !~ /Failed|Error/) {
     9    print "OK.\n";
    10  } else {
    11    print "There was an error.\n";
    12  }
    13
$ perl failtest.pl
OK.
$
```

I also had to change the match to a negation, and drop the ! from the initial if (from =~ to !~)  - after that the logic seems to work now.

many thanks for raising this issue

**Comment by richardforth** [comment]
Merged into master branch, can you please test it again for me?

**Comment by wiechu** [comment]
It's OK now, but I have few cosmetic notes:

*1)*
diff --git a/apache2buddy.pl b/apache2buddy.pl
index 885b964..7683c52 100644
--- a/apache2buddy.pl
+++ b/apache2buddy.pl
@@ -955,7 +955,7 @@ sub get_pid {
       # might return multiple values depending on Apache's listen
directives
       my @pids = `LANGUAGE=en_GB.UTF-8 netstat -ntap | egrep "LISTEN" |
grep \":$port \" | awk \'{ print \$7 }\' | cut -d / -f 1`;

-       print "VERBOSE: ".@pids." found listening on port 80\n" if
$main::VERBOSE;
+       print "VERBOSE: ".@pids." found listening on port $port\n" if
$main::VERBOSE;

       # set an initial, invalid PID.
       my $pid = 0;;

-----------------------------------------------
*2)* I don't like:

if ( $process_name eq 0 ) {


IMHO better is:

if ( 0 == $process_name ) {

or my favorite:

unless ( $process_name ) {


but it's perl and it's your code.
-----------------------------------------------
3) Also I don't like:

print "VERBOSE: UID of user is: ".$uid."\n" ...

IMHO better is:

print "VERBOSE: UID of user is: $uid\n" ...

but again – it's perl and it's your code.
-----------------------------------------------

BTW Thank you for apache2buddy.pl

Yours sincerely,
Wiesław Ochmiński







czw., 12 mar 2020 o 11:17 Richard Forth <notifications@github.com>
napisał(a):

**Comment by richardforth** [comment]
You're welcome  for it and make it how you like it, I also welcome PRs :) 

Just be careful not to break anything and rememeber it has to work on Ubuntu as well and CentOS (the big four):

- RHEL
- CentOS (& Scientific)
- Ubuntu
- Debian

Cosmetic changes should be fine.

I dont have a lot of time to spend on this so I really welcome PRs as it saves me a lot of time coding - but it is a labour of love. I do welcome your criticism, I know you want to make it better. Help me by forking it and doing a PR with all your changes, dont forget to update the md5sums and sha256 sums and the changelog as it speeds up merges.

Many thanks for your input, get your PR in and you can add your name to the contributors in the changelog :)

**Comment by richardforth** [comment]
Please also only PR from staging, as it gives me a chance to test if necessary without breaking the master branch  - I learnt that lesson the hard way when I was new to GitHub and git in general :)
