### ISSUE TITLE
Unable to locate pid file

### ISSUE THREAD

**Issue by kpsajeer** [richardforth/apache2buddy#326]
My server in centos 7, Apache/2.4.41, PHP 7.2.27 
When I run curl -sL https://raw.githubusercontent.com/richardforth/apache2buddy/master/apache2buddy.pl | perl

I am getting this error and exiting the code 

[ -- ] pidfile setting is CONFIG NOT FOUND.
Unsuccessful stat on filename containing newline at - line 1862 (#1)
    (W newline) A file operation was attempted on a filename, and that
    operation failed, PROBABLY because the filename contained a newline,
    PROBABLY because you forgot to chomp() it off.  See "chomp" in perlfunc.
    
[ !! ] Unable to locate pid file. Exiting.

**Comment by richardforth** [comment]
this might be resolved in a new pull request that was merged into staging, try this:

```bash
curl https://raw.githubusercontent.com/richardforth/apache2buddy/staging/apache2buddy.pl | perl
```

Im doing testing before pushing it live. let me know if the fix works in staging please.

Sorry updates are slow here, im a one man band with a full time job.

I appreciate your patience.

Kind regards
Richard

**Comment by kpsajeer** [comment]
Yes it works

Regards
Sajeer
