### ISSUE TITLE
event model

### ISSUE THREAD

**Issue by jasonwee** [richardforth/apache2buddy#350]
https://github.com/richardforth/apache2buddy/blob/1987db3991beb7b25d58f9ccc7f6d8b15c661be7/apache2buddy.pl#L1519

shouldn't that be event model?

**Comment by richardforth** [comment]
Yes I have noticed that too, it should actually say something like "Apache2buddy ONLY calculates MaxClients or MaxRequestWorkers for PreFork".

I will keep this open and get that wording changed. 

Thank you!
