### ISSUE TITLE
Unable to run apache2buddy even by user with root priviledges or Sudo 

### ISSUE THREAD

**Issue by eazuka** [richardforth/apache2buddy#354]
Thanks for this awesome script, though i'm having issue running this script.

When i try running this script, i get the below message:
**[ !! ] This script must be run as root.** 

The user/username running this script is not called **root** however the user/username has full root privileages. Also running the script with sudo still doesn't work, i get same message: **[ !! ] This script must be run as root.** 

**Any idea why this is happening even though i have full root privilages?**

I will appreciate help.

**Comment by richardforth** [comment]
It is looking for user with UID 0

```perl
	# Check 1
	# make sure the script is being run as root.
	# we need to run as root to ensure that we can access all of the appropriate
	# files
	my $uid = `id -u`;
	chomp($uid);

	print "VERBOSE: UID of user is: ".$uid."\n" if $VERBOSE;

	if ( $uid ne '0' ) {
		show_crit_box();
 	      	print "This script must be run as root.\n";
        	exit;
	} else {
		if ( ! $NOOK ) { show_ok_box(); print "This script is being run as root.\n" }
	}
```

I am not going to fix this for you because its been in the wild now for over 6 years. You have a nonstandard setup. Youre welcome to make a fork and tweak it for your own custom set up.
