### ISSUE TITLE
php 7.4: Error: Use of uninitialized value $real_config in concatenation (.) or string at line 1334

### ISSUE THREAD

**Issue by timdream** [richardforth/apache2buddy#355]
Thanks for offering apache2buddy to the world! Really helpful.

I am getting this non-fatal error from Perl when it attempts to get the PHP Memory Limit.

```
Use of uninitialized value $real_config in concatenation (.) or string at -
	line 1334 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.

    To help you figure out what was undefined, perl will try to tell you
    the name of the variable (if any) that was undefined.  In some cases
    it cannot do this, so it also tells you what operation you used the
    undefined value in.  Note, however, that perl optimizes your program
    and the operation displayed in the warning may not necessarily appear
    literally in your program.  For example, "that $foo" is usually
    optimized into "that " . $foo, and the warning will refer to the
    concatenation (.) operator, even though there is no . in
    your program.

Use of uninitialized value $apache_proc_php in concatenation (.) or string at -
	line 2491 (#1)
[ -- ] Your PHP Memory Limit (Per-Process) is .
```

Looking at line 1334

https://github.com/richardforth/apache2buddy/blob/7498e192e0e8494a85043640e3abc92e58317874/apache2buddy.pl#L1334

and try to run the command manually gave me this:

```
$ php -c $real_config -r "phpinfo(4);"
Could not open input file: phpinfo(4);
```

Apparently my Ubuntu is too new (20.04) and the correct path to the config file is `/etc/php/7.4/fpm/php.ini`. The logic above that line failed to find the path and set the `$real_config`.

I wonder if the script should be future-proof a bit more? Thanks.

**Comment by richardforth** [comment]
Hi TimDream,

It's almost impossible to future proof where Ubuntu is concerned, as each new release causes some kind of problem that I have to code around.

Ubuntu 20.04 was tested. but it seems I did'nt upload the Dockerfiles to make a comparison with. 

I will look into this and get back to you on this.

I beleive the thing that might be the issue in php7.4

I also see you quoted the path to php-fpm which wont be correct for php-cli.

You can try installing php-cli for your version of php, but I will look into this separately and get back to you.

Thanks for using apache2buddy!

Rich

**Comment by richardforth** [comment]
Ok so a quick update, I lost the Dockerfile, but I found the image i uploaded to docker hub, and inspecting the layers, i dont see where I installed php, so it looks like  this was an omission on my part.

Reconstructing the Dockerfile from the layer information we get the following:

```
FROM ubuntu:20.04
RUN apt-get update
RUN apt-get -y install curl
RUN apt-get -y install procps
RUN apt-get -y install net-tools
RUN apt-get -y install apache2
RUN apt-get -y install perl
RUN apt-get -y install python3
RUN apt-get -y install python3-distro
ENTRYPOINT ["/bin/sh" "-c" "service apache2 start && curl -sk https://raw.githubusercontent.com/richardforth/apache2buddy/staging/apache2buddy.pl | perl"]
```

This is a reconstruction based on layer info from docker hub, but my guess here is I didnt install php, so I apologise for that.

From looking at all the layers i dont see any reference to PHP at all.

I will need to re-do this one and test again using PHP. 

Thanks for highlighting this.

Kind Regards
Richard

**Comment by timdream** [comment]
Sorry I referenced the wrong file. `/etc/php/7.4/apache2/php.ini` exists on my system.

**Comment by richardforth** [comment]
Brilliant,

Thanks for the info - as I say - it looks like I  completely neglected to include PHP in my Dockerfiles, I'll be sure to update that and retest taking this issue into consideration. 

Normally I would have caught this but seems I gave them a greenlight without considering PHP as part of the build.

IF (and its a big IF) they stick to this format of folder structure:


/etc/php/7.4/apache2/php.ini

I might be able to do something to wildcard the version number portion of the directory to wildcard it as you say to make it a bit more future proofed.

I appreciate your input.




My apologies for that.

**Comment by richardforth** [comment]
If you dont see any activity here, may I please also ask you to monitor the following issue too #356 

It seem like I may have generated a whole bunch of work for myself so it may take a while to resolve this.

I'll obviously try and prioritise Ubuntu 20.04 with php7.4  but it looks like ALL the dockerfiles on all the supported platforms also have php missing from the builds. So as you can imagine this has created a ton of work and opened a catering pack sized can'o'worms for me to go and retest with php! 

It's of my own doing.  So I take it on the chin, and thanks again for raising this, it was a ticking time bomb I didnt realise I had set.

**Comment by richardforth** [comment]
Some sad violin music:
https://www.youtube.com/watch?v=-EQ6eHeBrhM

**Comment by richardforth** [comment]
Here is where it looks like the problems begin with PHP side of things:

https://github.com/richardforth/apache2buddy/blob/7498e192e0e8494a85043640e3abc92e58317874/apache2buddy.pl#L1309

Looks like I last tested with 7.3, but as you mentioned I cant keep adding if statements for each version,  need to try and glob the directories or something.

**Comment by richardforth** [comment]
I have mocked up a test script for testing purposes, its mimicking how the current development cycle seems to be going, wtih two new lines added:

```
root@server-01:~# vim phptest.pl
root@server-01:~# perl phptest.pl
[--] Locating php.ini...
[--] PHP located at: /etc/php/7.4/apache2/php.ini
[--] Done.
root@server-01:~# cat phptest.pl
#!/usr/bin/perl

use strict;
use warnings;

print "[--] Locating php.ini...\n";
if ( -f "/etc/php5/apache2/php.ini" ) {
        our $real_config = "/etc/php5/apache2/php.ini";
} elsif ( -f "/etc/php/7.0/apache2/php.ini") {
        our $real_config = "/etc/php/7.0/apache2/php.ini";
} elsif ( -f "/etc/php/7.0/fpm/php.ini") {
        our $real_config = "/etc/php/7.0/fpm/php.ini";
} elsif ( -f "/etc/php/7.1/apache2/php.ini") {
        our $real_config = "/etc/php/7.1/apache2/php.ini";
} elsif ( -f "/etc/php/7.1/fpm/php.ini") {
        our $real_config = "/etc/php/7.1/fpm/php.ini";
} elsif ( -f "/etc/php/7.2/apache2/php.ini") {
        our $real_config = "/etc/php/7.2/apache2/php.ini";
} elsif ( -f "/etc/php/7.2/fpm/php.ini") {
        our $real_config = "/etc/php/7.2/fpm/php.ini";
} elsif ( -f "/etc/php/7.3/apache2/php.ini") {
        our $real_config = "/etc/php/7.3/apache2/php.ini";
} elsif ( -f "/etc/php/7.3/fpm/php.ini") {
        our $real_config = "/etc/php/7.3/fpm/php.ini";
} elsif ( -f "/etc/php/7.4/apache2/php.ini") {
        our $real_config = "/etc/php/7.4/apache2/php.ini";
} elsif ( -f "/etc/php/7.4/fpm/php.ini") {
        our $real_config = "/etc/php/7.4/fpm/php.ini";
} else {
        our $real_config = "Not Found.";
}


our $real_config;
print "[--] PHP located at: $real_config\n";
print "[--] Done.\n";
root@server-01:~#
```

Im going to use this script as a basis for converting it to a more future proof system (because I cant keep exponentially growing this IF block):

Also of note is that it checks two different locations:

```perl
} elsif ( -f "/etc/php/7.4/apache2/php.ini") {
        our $real_config = "/etc/php/7.4/apache2/php.ini";
} elsif ( -f "/etc/php/7.4/fpm/php.ini") {
        our $real_config = "/etc/php/7.4/fpm/php.ini";
}
```

and this is the same throughout the 7.x history.

**Comment by richardforth** [comment]
so this is what I came up with in Perl:


```bash
root@server-01:~# perl phptest.pl
[--] Locating php.ini...
[--] PHP located at: /etc/php/7.4/apache2/php.ini
[--] Done.
```

```perl
root@server-01:~# cat phptest.pl
#!/usr/bin/perl
use strict;
use warnings;
print "[--] Locating php.ini...\n";
if ( -f "/etc/php5/apache2/php.ini" ) {
        our $real_config = "/etc/php5/apache2/php.ini";
} else {
        # looking for /etc/php/*/apache2/php.ini
        my @files = glob "/etc/php/*/apache2/php.ini";
        if (@files != 1) {
                # looking for /etc/php/*/fpm/php.ini
                my @files = glob "/etc/php/*/fpm/php.ini";
                if (@files != 1) {
                        our $real_config = "Not Found";
                }
        } else {
                our $real_config = $files[0];
        }
}
our $real_config;
print "[--] PHP located at: $real_config\n";
print "[--] Done.\n";
```

**Comment by richardforth** [comment]
Ok, should be patched now in staging:

root@server-01:~# curl -sk https://raw.githubusercontent.com/richardforth/apache2buddy/staging/apache2buddy.pl | perl
#####################################################
apache2buddy.pl report for server-01 (** redacted **)
#####################################################
[ OK ] This script is being run as root.
[ OK ] The utility 'pmap' exists and is available for use: /usr/bin/pmap
[ OK ] The utility 'netstat' exists and is available for use: /usr/bin/netstat
[ OK ] 'php' exists and is available for use: /usr/bin/php
[ OK ] The utility 'apachectl' exists and is available for use: /usr/sbin/apachectl
[ OK ] The port (port 80) is a valid port.
[ -- ] We are attempting to discover the operating system type and version number ...
[ !! ] Unable to locate the 'python' binary.
[ OK ] The 'python3' binary exists and is available for use: /usr/bin/python3
[ -- ] Distro: Ubuntu
[ -- ] Version: 20.04
[ -- ] Codename: focal
[ OK ] This distro is supported by apache2buddy.pl.
[ OK ] This distro version is supported by apache2buddy.pl.
[ -- ] Hostname: server-01
[ -- ] Primary IP: ** redacted **
[ -- ] We are checking the service running on port 80...
[ -- ] The process listening on port 80 is /usr/sbin/apache2
[ -- ] The process running on port 80 is Apache/2.4.41 (Ubuntu).
[ -- ] The full path to the Apache config file is: /etc/apache2/apache2.conf
[ -- ] Apache is using prefork model.
[ OK ] Running user (www-data) matches config (www-data).
[ -- ] pidfile setting is /var/run/apache2$SUFFIX/apache2.pid.
[ -- ] Actual pidfile is /var/run/apache2/apache2.pid.
[ -- ] Parent PID: 12187.
[ OK ] Memory usage of parent PID is less than 50MB: 5892 Kilobytes.
[ -- ] Apache has been running 0d 01h 11m 39s.
[ !! ] *** LOW UPTIME ***.
[ @@ ] The following recommendations may be misleading - apache has been restarted within the last 24 hours.
[ -- ] Your server has 974 MB of PHYSICAL memory.
[ >> ] ServerLimit directive not found, assuming default values.
[ -- ] Your ServerLimit setting is 256.
[ -- ] Your MaxRequestWorkers setting is 150.
[ OK ] Current Apache Process Count is 7, including the parent PID.
[ -- ] Number of vhosts detected: 0.
[ OK ] Current Apache vHost Count is less than maxrequestworkers.
[ @@ ] vHost Count works only when we have NameVirtualHosting enabled, check config manually, they may only have the default vhost.
[ >> ] MaxRequestsPerChild directive not found.
[ -- ] Your MaxConnectionsPerChild setting is 0.
[ -- ] This server is NOT running Plesk.
[ -- ] This server is NOT running cPanel.
[ -- ] This server is NOT running Virtualmin.
[ -- ] Your PHP Memory Limit (Per-Process) is 128M.
[ OK ] No additional services were detected.
[ OK ] No large log files were found in /var/log/apache2.
[ OK ] MaxClients has not been hit recently.
[ >> ] Apache only logs maxclients/maxrequestworkers hits once in a lifetime, if no restart has happened this event may have been rotated away.
[ >> ] As a backup check, please compare number of running apache processes (minus 1 for parent) against maxclients/maxrequestworkers.
[ >> ] For more information see https://github.com/apache/httpd/blob/0b61edca6cdda2737aa1d84a4526c5f9d2e23a8c/server/mpm/prefork/prefork.c#L809
[ OK ] No PHP Fatal Errors were found.
[ OK ] No package updates found.
[ -- ] apache2 is currently using 65.95 MB of memory.
[ -- ] The smallest apache process is using 5.92 MB of memory
[ -- ] The average apache process is using 5.92 MB of memory
[ -- ] The largest apache process is using 5.96 MB of memory
[ OK ] Going by the average Apache process, Apache can potentially use 888.00 MB RAM:
                Without considering services: 91.18 % of total installed RAM
                Considering extra services: 91.18 % of remaining RAM
[ OK ] Going by the largest Apache process, Apache can potentially use 894.00 MB RAM:
                Without considering services: 91.79 % of total installed RAM
                Considering extra services: 91.79 % of remaining RAM


--------------------------------------------------------------------------------
### GENERAL FINDINGS & RECOMMENDATIONS ###
--------------------------------------------------------------------------------
Apache2buddy.pl report for server: server-01 (** redacted **):

Settings considered for this report:
[ !! ] *** LOW UPTIME ***.
[ @@ ] The following recommendations may be misleading - apache has been restarted within the last 24 hours.

        Your server's physical RAM:                                   974 MB
        Remaining Memory after other services considered:             974 MB
        Apache's MaxRequestWorkers directive:                         150      <--------- Current Setting
        Apache MPM Model:                                             prefork
        Largest Apache process (by memory):                           5 MB
[ OK ]  Your MaxRequestWorkers setting is within an acceptable range.
        Your recommended MaxRequestWorkers setting (based on available memory) is between 146 and 163. <------- Acceptable Range (10% of MAX)
        Max potential memory usage:                                   894 MB
        Percentage of TOTAL RAM allocated to Apache:                  91.79  %
        Percentage of REMAINING RAM allocated to Apache:              91.79  %
--------------------------------------------------------------------------------
A log file entry has been made in: /var/log/apache2buddy.log for future reference.

Last 5 entries:

2020/09/09 09:39:44 Uptime: "0d 01h 11m 39s" Model: "Prefork" Memory: "974 MB" MaxRequestWorkers: "150" Recommended: "163" Smallest: "5.92 MB" Avg: "5.92 MB" Largest: "5.96 MB" Highest Pct Remaining RAM: "91.79%" (91.79% TOTAL RAM)

root@server-01:~#


Can you please test using the command above used to pull the script and run it  from staging? if that works I will merge into master branch.




VERBOSE:

VERBOSE: PHP: Loaded Configuration File => /etc/php/7.4/cli/php.ini
VERBOSE: PHP: Attempting to find real apache php.ini file...
VERBOSE: PHP: Real apache php.ini file is /etc/php/7.4/apache2/php.ini, using that...
[ -- ] Your PHP Memory Limit (Per-Process) is 128M.


CODE:

```perl
        if ( $config =~ /cli/ ) {
                if ($VERBOSE) { print "VERBOSE: PHP: Attempting to find real apache php.ini file...\n" }
                # try to find the apache2 one
                if ( -f "/etc/php5/apache2/php.ini" ) {
                        our $real_config = "/etc/php5/apache2/php.ini";
                } else {
                        # looking for /etc/php/*/apache2/php.ini
                        my @files = glob "/etc/php/*/apache2/php.ini";

                        if (@files != 1) {
                                # looking for /etc/php/*/fpm/php.ini
                                my @files = glob "/etc/php/*/fpm/php.ini";

                                # This block should never be hit.
                                if (@files != 1) {
                                        our $real_config = "Not Found.";
                                }
                        } else {
                                our $real_config = @files[0];
                        }
                }
```

**Comment by richardforth** [comment]
In case you missed it, im keeping this open until you've had a chance to test using the staging branch here:

```bash
 curl -sk https://raw.githubusercontent.com/richardforth/apache2buddy/staging/apache2buddy.pl | perl
```

If that works, I'll merge it into the master branch.

**Comment by timdream** [comment]
Yeah it worked. Thank you for the quick turnaround!

**Comment by richardforth** [comment]
Awesome, I will get this merged this morning.

Youre very welcome! :D

**Comment by richardforth** [comment]
Merged; closing.
