### ISSUE TITLE
No reference to PHP in Dockerfiles

### ISSUE THREAD

**Issue by richardforth** [richardforth/apache2buddy#356]
See #355

**Comment by richardforth** [comment]
I seem to have seeded the issue here in the Debian10 Dockerfile that I do have (for some reason I dont have any ubuntu Dockerfiles 
 uplloaded):

```
FROM debian:10
RUN  apt-get update
RUN  apt-get -y install curl
RUN  apt-get -y install procps
RUN  apt-get -y install net-tools
RUN  apt-get -y install apache2
RUN  apt-get -y install perl
RUN  apt-get -y install python3
ENTRYPOINT service apache2 start && curl -sk https://raw.githubusercontent.com/richardforth/apache2buddy/staging/apache2buddy.pl | perl
```

I would have copied this to generate the Ubuntu docker files, probably changing only the FROM line, so all the Debian Dockerfiles need updating and retesting too.

**Comment by richardforth** [comment]
Same with CentOS 6 through 8 

So looks like ALL Dockerfiles need to be redone, and updated images reuploaded to Docker hub and Dockerfiles re-submitted to github.

**Comment by richardforth** [comment]
Also Scientific 6 & 7 too, as that was based on the CentOS Dockerfile.

Scientific 8 wasnt out when I built them, but I will check - now is as good a time as any.

**Comment by richardforth** [comment]
apt-get install php on Ubuntu 20.04 defaults to 7.4 now which is great, means I dont have to faff about with third party repos. Makes updating the dockerfiles fairly straightforward.

**Comment by midnight-dev** [comment]
> apt-get install php on Ubuntu 20.04 defaults to 7.4 now

Sweet mercy. This is what I was waiting for. Developing for PHP with VS Code & WSL/Ubuntu is finally going to feel right without needing to waste time manually upgrading from 7.2. 🎉

**Comment by richardforth** [comment]
haha yeah no more dicking around with  third party PPAs
