### ISSUE TITLE
is this compomized?

### ISSUE THREAD

**Issue by mrhili** [richardforth/apache2buddy#372]
because my host is slow after runing it as root

cant be run in other way

**Comment by richardforth** [comment]
No. It's run in production for many years. and is safe.

**Comment by richardforth** [comment]
The only changes it makes is it writes a log file to
/var/log/apache2buddy.log.

There's no way any słowness can be attributed to running my script. It
doesn't make any other changes but needs the root access to gain
information from privileged configuration files such as the files in
/etc/httpd or /etc/apache2.

Without which the script can't do what it does.

There is no way to change this. My best advice is not to run it if you're
not comfortable with it as it is provided as is with no warranties or
guarantees.

What I can say is that we've been running this in production hosting
systems for many years without any issues. So I suspect that your host is
slow for other reasons.

**Comment by mrhili** [comment]
okay, I just want to be shoor.
