### ISSUE TITLE
Plans to Support AlmaLinux 8.x and CloudLinux 7.9?

### ISSUE THREAD

**Issue by jivemedia** [richardforth/apache2buddy#381]
Hello, as the title states - will these OS be supported in the near future?

Great script, would love to see these OS be supported.

Cheers :)

**Comment by jivemedia** [comment]
Apologies, just noticed that you won't be supporting any further OS!

**Comment by richardforth** [comment]
Hi Jivemedia.

Thanks for the feedback, I don't have much time to spend developing this any more, CentOS 8 and Cloudlinux are not on the roadmap at all, but I may well look into getting it supported on Alma and  Rocky.

Kind Regards
Richard

**Comment by richardforth** [comment]
I've managed to build myself a Jenkins pipeline and i found a Docker image for RockyLinux 8 and I've just seen an AlmaLinux  docker image I can test against too.

https://hub.docker.com/r/almalinux/almalinux

**Comment by richardforth** [comment]
I added support for AlmaLinux 8, but I could'nt find an official / trusted docker image for CloudLinux 7.9 to test against.

**Comment by jivemedia** [comment]
Awesome, thanks so much!
