### ISSUE TITLE
--- a2bchk.sh --- showing MD5 mismatch

### ISSUE THREAD

**Issue by dakman** [richardforth/apache2buddy#402]
![image](https://user-images.githubusercontent.com/2136346/198865605-974741cc-91ef-4ef0-a7c2-bc9502e3d20d.png)

prolly an issue with the comparison/ if statement  or how you are cutting the string

**Comment by dakman** [comment]
oops was using sh to run it  ... make sure u chmod and ./a2bchk.sh to use /bin/bash or it will error out

**Comment by dakman** [comment]
i didnt catch this cause i saw .sh at the end thinking this script didnt have the /bin/bash env at the top

**Comment by richardforth** [comment]
Thanks for checking the MD5UMs!

I've re-opened this issue as it reminded me that I need to add this to the Jenkinsfile to make sure the Jenkins tests pick up the MD5 and SHA256 sums match during the testing pipeline.

As you can see from your screenshot, the MD5 sums matched anyway, I'm still not 100% sure why it failed like that but youre right, either chmodding it 700 or 755 and ./a2bchk.sh or source a2bchk.sh should both work.

I always put a shebang line at the top of all my scripts so Ive never called one with sh before.

Anyway thanks for raising this, as soon as I've added it in to the jenkins pipeline and tested, I'll close this one off again.

**Comment by richardforth** [comment]
Added to all stages of the Jenkinsfile
