### ISSUE TITLE
Support for SLES 12 with worker MPM

### ISSUE THREAD

**Issue by jhaeringk1** [richardforth/apache2buddy#413]
For Support for SLES 12/15 with worker MPM you have to add thes **httpd-worker** and **/usr/sbin/httpd-worker** to the following lines, because SLES 12/15 uses an "-" instead of an ".".

```perl
### Line 1786
my @process_info = split(' ', `ps -C 'httpd httpd.worker httpd-worker apache apache2 /usr/sbin/httpd /usr/sbin/httpd.worker /usr/sbin/httpd-worker' -f | grep '^root'`);

### Line 1835
my @process_info = split(' ', `ps -C 'httpd httpd.worker httpd-worker apache apache2 /usr/sbin/httpd /usr/sbin/httpd.worker /usr/sbin/httpd-worker' -f | grep '^root'`);

**Comment by richardforth** [comment]
Hi, apache2buddy was only ever written to support prefork mode, for work mode, all the php offloading is done by fastcgi and php-fpm, which is out of scope. Try php-fpmpal which was designed to work with php-fpm
