### ISSUE TITLE
Find DocumentRoot, ErrorLog, CustomLog for vhosts

### ISSUE THREAD

**Issue by josephchapman** [richardforth/apache2buddy#7]
A task that's not particularly time consuming (but is performed every time) is the location of a vhost, its configuration file, and its relevant details.

e.g.

1)  See what's hosted
    # httpd -S
2) Obviously there'll be millions of vhosts, so filter the one you're interested in
    # httpd -S 2>&1 | grep 'example.com'
3) Now that you've returned a line containing the configuration file, find the juicy bits of it
    # grep -E '^\s*(DocumentRoot|ErrorLog|CustomLog)' /etc/httpd/vhost.d/example.com.conf

Displaying those three directives for every vhost will spam up the output if there are too many.  Perhaps add logic to only display those things if there are 5 or fewer vhosts.

**Comment by richardforth** [comment]
Decided not to implement this at this time
