### ISSUE TITLE
Unable to open pid file

### ISSUE THREAD

**Issue by SnAFKe** [richardforth/apache2buddy#84]
Hi,

I'm running cPanel and when is looking for a pid the script stop.

[ INFO     ] OS Name: CentOS
[ INFO     ] OS Release: 6.8
[ OK       ] Apache2buddy supports this OS Release/Version.
[ INFO     ] We are checking the service running on port 80...
[ INFO     ] The process listening on port 80 is /usr/sbin/httpd
[ INFO     ] The process running on port 80 is Apache/2.4.23 (cPanel).
[ INFO     ] Apache has been running 70d 13h 16m 31s.
[ INFO     ] The full path to the Apache config file is: /etc/apache2/conf/httpd                                                                                                                                                                                               .conf
[ INFO     ] Apache is using event model.
[ WARNING  ] Non-standard apache set-up, apache is running as UID: 99 (nobody).                                                                                                                                                                                    Expecting UID 48 ('apache' or 'www-data').
[ INFO     ] Apache runs as nobody.
[ INFO     ] pidfile setting is /etc/apache2/run/httpd.pid.
[ CRITICAL ] Unable to open pid file /var/run/httpd/httpd.pid. Exiting.

**Comment by richardforth** [comment]
Hi yes this is a bug

You can work around it by specifying the--no-check-pid option.

Thanks for reporting!
