### ISSUE TITLE
Wrong MPM information

### ISSUE THREAD

**Issue by SnAFKe** [richardforth/apache2buddy#85]
Hi,

I'm currect not sure if this is a bug but i'm getting wrong MPM information

Currectly i'm running prefork your script detect it all fine here.

The problem is the values is getting information from ITK instead of Prefork

[ INFO     ] OS Name: CentOS
[ INFO     ] OS Release: 6.8
[ OK       ] Apache2buddy supports this OS Release/Version.
[ INFO     ] We are checking the service running on port 80...
[ INFO     ] The process listening on port 80 is nginx:
[ INFO     ] The process running on port 80 is not Apache. Falling back to proce                                                                                                                                                                                               ss list...
[ INFO     ] Apache is actually listening on port 8080
[ INFO     ] The process running on port 8080 is Apache/2.2.15 (Unix).
[ INFO     ] Apache has been running 4d 09h 45m 14s.
[ INFO     ] The full path to the Apache config file is: /etc/httpd/conf/httpd.c                                                                                                                                                                                               onf
[ INFO     ] Apache is using prefork model.
[ INFO     ] pidfile setting is run/httpd.pid.
[ INFO     ] Actual pidfile is /var/run/httpd/httpd.pid.
[ INFO     ] Parent PID: 3608.
[ OK       ] Memory usage of parent PID is less than 50MB: 10824 Kilobytes.
[ INFO     ] Your server has 32129 MB of PHYSICAL memory.
[ INFO     ] Your ServerLimit setting is 256.
[ INFO     ] Your MaxClients setting is 256.
[ OK       ] Current Apache Process Count is 54, including the parent PID.
[ INFO     ] Number of vhosts detected: 5.
[ OK       ] Current Apache vHost Count is less than maxclients.
[ INFO     ] Your MaxRequestsPerChild setting is 4000.

Perfork setting is not that if not the ITK its report the same values.

**Comment by richardforth** [comment]
Hi I'm not sure what you mean.

Apache2buddy.pl doesn't support itk so should only be pulling info on
prefork.

Can you please share the relevant sections of your httpd.conf

Also --verbose output might be useful

**Comment by richardforth** [comment]
I figured out what's wrong.

I'm not actively ignoring itk settings and default behaviour is to use the
last entry as the setting to trust (given that apache configs are read in
order.

I'm not at my pc but will address both bugs you raised within the next day
or two.

If you're interested in making a pull request the subroutine at fault is
find_master_value.

It was written a long time ago when we only had prefork and worker. You'll
see I added ignores for event but I need to do similar to ignore itk
settings.

Hope that helps. So yes it's definitely a bug.

And no - before you ask - itk mpm will never be supported. There are closed
threads related to why not.


On 25 Jan 2017 18:16, "Richard Forth" <richard.forth@gmail.com> wrote:

Hi I'm not sure what you mean.

Apache2buddy.pl doesn't support itk so should only be pulling info on
prefork.

Can you please share the relevant sections of your httpd.conf

Also --verbose output might be useful

**Comment by SnAFKe** [comment]
Definity that cause the issue i not test it but seems logical.

prefork.c > worker.c > itk.c

itk is the last entry, also add event support.

**Comment by richardforth** [comment]
apache2buddy only supports prefork,
worker mode isnt really supported
event definately isnt, and neither is ITK

I've made a commit that now addresses the issues you had where ITK wasnt being ignored so you should now get the right information.

Ive also added a block of code that detects if the ITK module is loaded, and exits. 

This because ITK also requires prefork to be loaded too, so its as confusing as hell determining the actual MPM, (unlike event, prefork and worker where only one module of these will be loaded at one time.

TGhis does mean that ive probably broken it more for you, if youre really running ITK (the module appears as a loaded module):


Prefork Mode 

```
[root@git apache2buddy]# apachectl -M 2>&1 | egrep "prefork|worker|event|itk"
 mpm_prefork_module (shared)
```

With ITK Loaded:

```
[root@git apache2buddy]# apachectl -M 2>&1 | egrep "prefork|worker|event|itk"
 mpm_itk_module (shared)
 mpm_prefork_module (shared)
```


Net result:

```
[root@git apache2buddy]# curl -sL apache2buddy.pl | perl - --report
[ CRITICAL ] MPM ITK was detected, apache2buddy.pl does odd things so we quit. Sorry.
[ ADVISORY ] MPM ITK is not supported. Unload the module and try again.
```
